"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgSlashValidator(google.protobuf.message.Message):
    """MsgSlashValidator is the Msg/SlashValidator request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    VALIDATOR_ADDRESS_FIELD_NUMBER: builtins.int
    INFRACTION_HEIGHT_FIELD_NUMBER: builtins.int
    TOKENS_AT_INFRACTION_HEIGHT_FIELD_NUMBER: builtins.int
    SLASH_FACTOR_FIELD_NUMBER: builtins.int
    authority: builtins.str
    validator_address: builtins.str
    """Consensus address of the validator to slash"""
    infraction_height: builtins.int
    """Colloquially, the height at which the validator is deemed to have
    misbehaved. In practice, this is the height used to determine the targets
    of the slash. For example, undelegating after this height will not escape
    slashing. This height should be set to a recent height at the time of the
    proposal to prevent delegators from undelegating during the vote period.
    i.e. infraction_height <= proposal submission height.

    NB: At the time this message is applied, this height must have occured
    equal to or less than an unbonding period in the past in order for the
    slash to be effective.
    i.e. time(proposal pass height) - time(infraction_height) < unbonding
    period
    """
    tokens_at_infraction_height: builtins.bytes
    """Tokens of the validator at the specified height. Used to compute the slash
    amount. The x/staking HistoricalInfo query endpoint can be used to find
    this.
    """
    slash_factor: builtins.str
    """Multiplier for how much of the validator's stake should be slashed.
    slash_factor * tokens_at_infraction_height = tokens slashed
    """
    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        validator_address: builtins.str = ...,
        infraction_height: builtins.int = ...,
        tokens_at_infraction_height: builtins.bytes = ...,
        slash_factor: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "infraction_height", b"infraction_height", "slash_factor", b"slash_factor", "tokens_at_infraction_height", b"tokens_at_infraction_height", "validator_address", b"validator_address"]) -> None: ...

global___MsgSlashValidator = MsgSlashValidator

@typing.final
class MsgSlashValidatorResponse(google.protobuf.message.Message):
    """MsgSlashValidatorResponse is the Msg/SlashValidator response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgSlashValidatorResponse = MsgSlashValidatorResponse
