"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dydxprotocol.accountplus.accountplus_pb2
import dydxprotocol.accountplus.models_pb2
import dydxprotocol.accountplus.params_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AuthenticatorData(google.protobuf.message.Message):
    """AuthenticatorData represents a genesis exported account with Authenticators.
    The address is used as the key, and the account authenticators are stored in
    the authenticators field.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    AUTHENTICATORS_FIELD_NUMBER: builtins.int
    address: builtins.str
    """address is an account address, one address can have many authenticators"""
    @property
    def authenticators(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.accountplus.models_pb2.AccountAuthenticator]:
        """authenticators are the account's authenticators, these can be multiple
        types including SignatureVerification, AllOfs, CosmWasmAuthenticators, etc
        """

    def __init__(
        self,
        *,
        address: builtins.str = ...,
        authenticators: collections.abc.Iterable[dydxprotocol.accountplus.models_pb2.AccountAuthenticator] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "authenticators", b"authenticators"]) -> None: ...

global___AuthenticatorData = AuthenticatorData

@typing.final
class GenesisState(google.protobuf.message.Message):
    """Module genesis state"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTS_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    NEXT_AUTHENTICATOR_ID_FIELD_NUMBER: builtins.int
    AUTHENTICATOR_DATA_FIELD_NUMBER: builtins.int
    next_authenticator_id: builtins.int
    """next_authenticator_id is the next available authenticator ID."""
    @property
    def accounts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.accountplus.accountplus_pb2.AccountState]: ...
    @property
    def params(self) -> dydxprotocol.accountplus.params_pb2.Params:
        """params define the parameters for the authenticator module."""

    @property
    def authenticator_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AuthenticatorData]:
        """authenticator_data contains the data for multiple accounts, each with their
        authenticators.
        """

    def __init__(
        self,
        *,
        accounts: collections.abc.Iterable[dydxprotocol.accountplus.accountplus_pb2.AccountState] | None = ...,
        params: dydxprotocol.accountplus.params_pb2.Params | None = ...,
        next_authenticator_id: builtins.int = ...,
        authenticator_data: collections.abc.Iterable[global___AuthenticatorData] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["accounts", b"accounts", "authenticator_data", b"authenticator_data", "next_authenticator_id", b"next_authenticator_id", "params", b"params"]) -> None: ...

global___GenesisState = GenesisState
