"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dydxprotocol.accountplus.accountplus_pb2
import dydxprotocol.accountplus.models_pb2
import dydxprotocol.accountplus.params_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AccountStateRequest(google.protobuf.message.Message):
    """AccountStateRequest is request type for the Query/AccountState RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    address: builtins.str
    def __init__(
        self,
        *,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address"]) -> None: ...

global___AccountStateRequest = AccountStateRequest

@typing.final
class AccountStateResponse(google.protobuf.message.Message):
    """AccountStateResponse is response type for the Query/GetAccountState RPC
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_STATE_FIELD_NUMBER: builtins.int
    @property
    def account_state(self) -> dydxprotocol.accountplus.accountplus_pb2.AccountState: ...
    def __init__(
        self,
        *,
        account_state: dydxprotocol.accountplus.accountplus_pb2.AccountState | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account_state", b"account_state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_state", b"account_state"]) -> None: ...

global___AccountStateResponse = AccountStateResponse

@typing.final
class QueryParamsRequest(google.protobuf.message.Message):
    """QueryParamsRequest is request type for the Query/Params RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryParamsRequest = QueryParamsRequest

@typing.final
class QueryParamsResponse(google.protobuf.message.Message):
    """QueryParamsResponse is response type for the Query/Params RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAMS_FIELD_NUMBER: builtins.int
    @property
    def params(self) -> dydxprotocol.accountplus.params_pb2.Params:
        """params holds all the parameters of this module."""

    def __init__(
        self,
        *,
        params: dydxprotocol.accountplus.params_pb2.Params | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["params", b"params"]) -> None: ...

global___QueryParamsResponse = QueryParamsResponse

@typing.final
class GetAuthenticatorsRequest(google.protobuf.message.Message):
    """MsgGetAuthenticatorsRequest defines the Msg/GetAuthenticators request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    account: builtins.str
    def __init__(
        self,
        *,
        account: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account", b"account"]) -> None: ...

global___GetAuthenticatorsRequest = GetAuthenticatorsRequest

@typing.final
class GetAuthenticatorsResponse(google.protobuf.message.Message):
    """MsgGetAuthenticatorsResponse defines the Msg/GetAuthenticators response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_AUTHENTICATORS_FIELD_NUMBER: builtins.int
    @property
    def account_authenticators(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.accountplus.models_pb2.AccountAuthenticator]: ...
    def __init__(
        self,
        *,
        account_authenticators: collections.abc.Iterable[dydxprotocol.accountplus.models_pb2.AccountAuthenticator] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_authenticators", b"account_authenticators"]) -> None: ...

global___GetAuthenticatorsResponse = GetAuthenticatorsResponse

@typing.final
class GetAuthenticatorRequest(google.protobuf.message.Message):
    """MsgGetAuthenticatorRequest defines the Msg/GetAuthenticator request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    AUTHENTICATOR_ID_FIELD_NUMBER: builtins.int
    account: builtins.str
    authenticator_id: builtins.int
    def __init__(
        self,
        *,
        account: builtins.str = ...,
        authenticator_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "authenticator_id", b"authenticator_id"]) -> None: ...

global___GetAuthenticatorRequest = GetAuthenticatorRequest

@typing.final
class GetAuthenticatorResponse(google.protobuf.message.Message):
    """MsgGetAuthenticatorResponse defines the Msg/GetAuthenticator response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_AUTHENTICATOR_FIELD_NUMBER: builtins.int
    @property
    def account_authenticator(self) -> dydxprotocol.accountplus.models_pb2.AccountAuthenticator: ...
    def __init__(
        self,
        *,
        account_authenticator: dydxprotocol.accountplus.models_pb2.AccountAuthenticator | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account_authenticator", b"account_authenticator"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_authenticator", b"account_authenticator"]) -> None: ...

global___GetAuthenticatorResponse = GetAuthenticatorResponse
