"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PerpetualPosition(google.protobuf.message.Message):
    """PerpetualPositions are an account’s positions of a `Perpetual`.
    Therefore they hold any information needed to trade perpetuals.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PERPETUAL_ID_FIELD_NUMBER: builtins.int
    QUANTUMS_FIELD_NUMBER: builtins.int
    FUNDING_INDEX_FIELD_NUMBER: builtins.int
    QUOTE_BALANCE_FIELD_NUMBER: builtins.int
    perpetual_id: builtins.int
    """The `Id` of the `Perpetual`."""
    quantums: builtins.bytes
    """The size of the position in base quantums."""
    funding_index: builtins.bytes
    """The funding_index of the `Perpetual` the last time this position was
    settled.
    """
    quote_balance: builtins.bytes
    """The quote_balance of the `Perpetual`."""
    def __init__(
        self,
        *,
        perpetual_id: builtins.int = ...,
        quantums: builtins.bytes = ...,
        funding_index: builtins.bytes = ...,
        quote_balance: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["funding_index", b"funding_index", "perpetual_id", b"perpetual_id", "quantums", b"quantums", "quote_balance", b"quote_balance"]) -> None: ...

global___PerpetualPosition = PerpetualPosition
