"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.listing.params_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines `x/listing`'s genesis state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HARD_CAP_FOR_MARKETS_FIELD_NUMBER: builtins.int
    LISTING_VAULT_DEPOSIT_PARAMS_FIELD_NUMBER: builtins.int
    hard_cap_for_markets: builtins.int
    """hard_cap_for_markets is the hard cap for the number of markets that can be
    listed
    """
    @property
    def listing_vault_deposit_params(self) -> dydxprotocol.listing.params_pb2.ListingVaultDepositParams:
        """listing_vault_deposit_params is the params for PML megavault deposits"""

    def __init__(
        self,
        *,
        hard_cap_for_markets: builtins.int = ...,
        listing_vault_deposit_params: dydxprotocol.listing.params_pb2.ListingVaultDepositParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["listing_vault_deposit_params", b"listing_vault_deposit_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["hard_cap_for_markets", b"hard_cap_for_markets", "listing_vault_deposit_params", b"listing_vault_deposit_params"]) -> None: ...

global___GenesisState = GenesisState
