"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.listing.params_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryMarketsHardCap(google.protobuf.message.Message):
    """Queries for the hard cap on listed markets"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryMarketsHardCap = QueryMarketsHardCap

@typing.final
class QueryMarketsHardCapResponse(google.protobuf.message.Message):
    """Response type indicating the hard cap on listed markets"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HARD_CAP_FIELD_NUMBER: builtins.int
    hard_cap: builtins.int
    def __init__(
        self,
        *,
        hard_cap: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hard_cap", b"hard_cap"]) -> None: ...

global___QueryMarketsHardCapResponse = QueryMarketsHardCapResponse

@typing.final
class QueryListingVaultDepositParams(google.protobuf.message.Message):
    """Queries the listing vault deposit params"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryListingVaultDepositParams = QueryListingVaultDepositParams

@typing.final
class QueryListingVaultDepositParamsResponse(google.protobuf.message.Message):
    """Response type for QueryListingVaultDepositParams"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAMS_FIELD_NUMBER: builtins.int
    @property
    def params(self) -> dydxprotocol.listing.params_pb2.ListingVaultDepositParams: ...
    def __init__(
        self,
        *,
        params: dydxprotocol.listing.params_pb2.ListingVaultDepositParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["params", b"params"]) -> None: ...

global___QueryListingVaultDepositParamsResponse = QueryListingVaultDepositParamsResponse
