# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/airdrop/genesis.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from stride.airdrop import airdrop_pb2 as stride_dot_airdrop_dot_airdrop__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cstride/airdrop/genesis.proto\x12\x0estride.airdrop\x1a\x14gogoproto/gogo.proto\x1a\x1cstride/airdrop/airdrop.proto"\xec\x01\n\x0cGenesisState\x12=\n\x06params\x18\x01 \x01(\x0b\x32\x16.stride.airdrop.ParamsB\x15\xc8\xde\x1f\x00\xf2\xde\x1f\ryaml:"params"\x12\x42\n\x08\x61irdrops\x18\x02 \x03(\x0b\x32\x17.stride.airdrop.AirdropB\x17\xc8\xde\x1f\x00\xf2\xde\x1f\x0fyaml:"airdrops"\x12Y\n\x10user_allocations\x18\x03 \x03(\x0b\x32\x1e.stride.airdrop.UserAllocationB\x1f\xc8\xde\x1f\x00\xf2\xde\x1f\x17yaml:"user_allocations"B3Z1github.com/Stride-Labs/stride/v24/x/airdrop/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.airdrop.genesis_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z1github.com/Stride-Labs/stride/v24/x/airdrop/types"
    )
    _globals["_GENESISSTATE"].fields_by_name["params"]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "params"
    ]._serialized_options = b'\310\336\037\000\362\336\037\ryaml:"params"'
    _globals["_GENESISSTATE"].fields_by_name["airdrops"]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "airdrops"
    ]._serialized_options = b'\310\336\037\000\362\336\037\017yaml:"airdrops"'
    _globals["_GENESISSTATE"].fields_by_name["user_allocations"]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "user_allocations"
    ]._serialized_options = b'\310\336\037\000\362\336\037\027yaml:"user_allocations"'
    _globals["_GENESISSTATE"]._serialized_start = 101
    _globals["_GENESISSTATE"]._serialized_end = 337
# @@protoc_insertion_point(module_scope)
