"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MarketPrice(google.protobuf.message.Message):
    """MarketPrice is used by the application to store/retrieve oracle price."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EXPONENT_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Unique, sequentially-generated value that matches `MarketParam`."""
    exponent: builtins.int
    """Static value. The exponent of the price. See the comment on the duplicate
    MarketParam field for more information.

    As of v7.1.x, this value is determined from the marketmap instead of
    needing to match the MarketParam field.
    """
    price: builtins.int
    """The variable value that is updated by oracle price updates. `0` if it has
    never been updated, `>0` otherwise.
    """
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        exponent: builtins.int = ...,
        price: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["exponent", b"exponent", "id", b"id", "price", b"price"]) -> None: ...

global___MarketPrice = MarketPrice
