"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dydxprotocol.prices.market_param_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgCreateOracleMarket(google.protobuf.message.Message):
    """MsgCreateOracleMarket is a message used by x/gov for creating a new oracle
    market.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    authority: builtins.str
    """The address that controls the module."""
    @property
    def params(self) -> dydxprotocol.prices.market_param_pb2.MarketParam:
        """`params` defines parameters for the new oracle market."""

    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        params: dydxprotocol.prices.market_param_pb2.MarketParam | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "params", b"params"]) -> None: ...

global___MsgCreateOracleMarket = MsgCreateOracleMarket

@typing.final
class MsgCreateOracleMarketResponse(google.protobuf.message.Message):
    """MsgCreateOracleMarketResponse defines the CreateOracleMarket response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgCreateOracleMarketResponse = MsgCreateOracleMarketResponse

@typing.final
class MsgUpdateMarketPrices(google.protobuf.message.Message):
    """MsgUpdateMarketPrices is a request type for the UpdateMarketPrices method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MarketPrice(google.protobuf.message.Message):
        """MarketPrice represents a price update for a single market"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MARKET_ID_FIELD_NUMBER: builtins.int
        PRICE_FIELD_NUMBER: builtins.int
        market_id: builtins.int
        """The id of market to update"""
        price: builtins.int
        """The updated price"""
        def __init__(
            self,
            *,
            market_id: builtins.int = ...,
            price: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["market_id", b"market_id", "price", b"price"]) -> None: ...

    MARKET_PRICE_UPDATES_FIELD_NUMBER: builtins.int
    @property
    def market_price_updates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MsgUpdateMarketPrices.MarketPrice]: ...
    def __init__(
        self,
        *,
        market_price_updates: collections.abc.Iterable[global___MsgUpdateMarketPrices.MarketPrice] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["market_price_updates", b"market_price_updates"]) -> None: ...

global___MsgUpdateMarketPrices = MsgUpdateMarketPrices

@typing.final
class MsgUpdateMarketPricesResponse(google.protobuf.message.Message):
    """MsgUpdateMarketPricesResponse defines the MsgUpdateMarketPrices response
    type.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgUpdateMarketPricesResponse = MsgUpdateMarketPricesResponse

@typing.final
class MsgUpdateMarketParam(google.protobuf.message.Message):
    """MsgUpdateMarketParam is a message used by x/gov for updating the parameters
    of an oracle market.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    MARKET_PARAM_FIELD_NUMBER: builtins.int
    authority: builtins.str
    @property
    def market_param(self) -> dydxprotocol.prices.market_param_pb2.MarketParam:
        """The market param to update. Each field must be set."""

    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        market_param: dydxprotocol.prices.market_param_pb2.MarketParam | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["market_param", b"market_param"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "market_param", b"market_param"]) -> None: ...

global___MsgUpdateMarketParam = MsgUpdateMarketParam

@typing.final
class MsgUpdateMarketParamResponse(google.protobuf.message.Message):
    """MsgUpdateMarketParamResponse defines the UpdateMarketParam response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgUpdateMarketParamResponse = MsgUpdateMarketParamResponse
