# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osmosis/concentratedliquidity/params.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n*osmosis/concentratedliquidity/params.proto\x12\x1dosmosis.concentratedliquidity\x1a\x14gogoproto/gogo.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb9\x05\n\x06Params\x12\x43\n\x17\x61uthorized_tick_spacing\x18\x01 \x03(\x04\x42\"\xf2\xde\x1f\x1eyaml:\"authorized_tick_spacing\"\x12j\n\x19\x61uthorized_spread_factors\x18\x02 \x03(\tBG\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDec\xf2\xde\x1f yaml:\"authorized_spread_factors\"\x12v\n\x1f\x62\x61lancer_shares_reward_discount\x18\x03 \x01(\tBM\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDec\xf2\xde\x1f&yaml:\"balancer_shares_reward_discount\"\x12r\n\x12\x61uthorized_uptimes\x18\x05 \x03(\x0b\x32\x19.google.protobuf.DurationB;\xc8\xde\x1f\x00\xea\xde\x1f\x12\x64uration,omitempty\xf2\xde\x1f\x19yaml:\"authorized_uptimes\"\x98\xdf\x1f\x01\x12\x63\n\'is_permissionless_pool_creation_enabled\x18\x06 \x01(\x08\x42\x32\xf2\xde\x1f.yaml:\"is_permissionless_pool_creation_enabled\"\x12[\n#unrestricted_pool_creator_whitelist\x18\x07 \x03(\tB.\xf2\xde\x1f*yaml:\"unrestricted_pool_creator_whitelist\"\x12\x31\n\x0ehook_gas_limit\x18\x08 \x01(\x04\x42\x19\xf2\xde\x1f\x15yaml:\"hook_gas_limit\"J\x04\x08\x04\x10\x05R\x17\x61uthorized_quote_denomsBDZBgithub.com/osmosis-labs/osmosis/v25/x/concentrated-liquidity/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osmosis.concentratedliquidity.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/osmosis-labs/osmosis/v25/x/concentrated-liquidity/types'
    _globals['_PARAMS'].fields_by_name['authorized_tick_spacing']._loaded_options = None
    _globals['_PARAMS'].fields_by_name[
        'authorized_tick_spacing'
    ]._serialized_options = b'\362\336\037\036yaml:\"authorized_tick_spacing\"'
    _globals['_PARAMS'].fields_by_name['authorized_spread_factors']._loaded_options = None
    _globals['_PARAMS'].fields_by_name[
        'authorized_spread_factors'
    ]._serialized_options = (
        b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec\362\336\037 yaml:\"authorized_spread_factors\"'
    )
    _globals['_PARAMS'].fields_by_name['balancer_shares_reward_discount']._loaded_options = None
    _globals['_PARAMS'].fields_by_name[
        'balancer_shares_reward_discount'
    ]._serialized_options = b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec\362\336\037&yaml:\"balancer_shares_reward_discount\"'
    _globals['_PARAMS'].fields_by_name['authorized_uptimes']._loaded_options = None
    _globals['_PARAMS'].fields_by_name[
        'authorized_uptimes'
    ]._serialized_options = (
        b'\310\336\037\000\352\336\037\022duration,omitempty\362\336\037\031yaml:\"authorized_uptimes\"\230\337\037\001'
    )
    _globals['_PARAMS'].fields_by_name['is_permissionless_pool_creation_enabled']._loaded_options = None
    _globals['_PARAMS'].fields_by_name[
        'is_permissionless_pool_creation_enabled'
    ]._serialized_options = b'\362\336\037.yaml:\"is_permissionless_pool_creation_enabled\"'
    _globals['_PARAMS'].fields_by_name['unrestricted_pool_creator_whitelist']._loaded_options = None
    _globals['_PARAMS'].fields_by_name[
        'unrestricted_pool_creator_whitelist'
    ]._serialized_options = b'\362\336\037*yaml:\"unrestricted_pool_creator_whitelist\"'
    _globals['_PARAMS'].fields_by_name['hook_gas_limit']._loaded_options = None
    _globals['_PARAMS'].fields_by_name[
        'hook_gas_limit'
    ]._serialized_options = b'\362\336\037\025yaml:\"hook_gas_limit\"'
    _globals['_PARAMS']._serialized_start = 132
    _globals['_PARAMS']._serialized_end = 829
# @@protoc_insertion_point(module_scope)
