"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Params(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORIZED_TICK_SPACING_FIELD_NUMBER: builtins.int
    AUTHORIZED_SPREAD_FACTORS_FIELD_NUMBER: builtins.int
    BALANCER_SHARES_REWARD_DISCOUNT_FIELD_NUMBER: builtins.int
    AUTHORIZED_UPTIMES_FIELD_NUMBER: builtins.int
    IS_PERMISSIONLESS_POOL_CREATION_ENABLED_FIELD_NUMBER: builtins.int
    UNRESTRICTED_POOL_CREATOR_WHITELIST_FIELD_NUMBER: builtins.int
    HOOK_GAS_LIMIT_FIELD_NUMBER: builtins.int
    balancer_shares_reward_discount: builtins.str
    """balancer_shares_reward_discount is the rate by which incentives flowing
    from CL to Balancer pools will be discounted to encourage LPs to migrate.
    e.g. a rate of 0.05 means Balancer LPs get 5% less incentives than full
    range CL LPs.
    This field can range from (0,1]. If set to 1, it indicates that all
    incentives stay at cl pool.
    """
    is_permissionless_pool_creation_enabled: builtins.bool
    """is_permissionless_pool_creation_enabled is a boolean that determines if
    concentrated liquidity pools can be created via message. At launch,
    we consider allowing only governance to create pools, and then later
    allowing permissionless pool creation by switching this flag to true
    with a governance proposal.
    """
    hook_gas_limit: builtins.int
    @property
    def authorized_tick_spacing(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """authorized_tick_spacing is an array of uint64s that represents the tick
        spacing values concentrated-liquidity pools can be created with. For
        example, an authorized_tick_spacing of [1, 10, 30] allows for pools
        to be created with tick spacing of 1, 10, or 30.
        """

    @property
    def authorized_spread_factors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def authorized_uptimes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.duration_pb2.Duration]: ...
    @property
    def unrestricted_pool_creator_whitelist(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """unrestricted_pool_creator_whitelist is a list of addresses that are
        allowed to bypass restrictions on permissionless supercharged pool
        creation, like pool_creation_enabled, restricted quote assets, no
        double creation of pools, etc.
        """

    def __init__(
        self,
        *,
        authorized_tick_spacing: collections.abc.Iterable[builtins.int] | None = ...,
        authorized_spread_factors: collections.abc.Iterable[builtins.str] | None = ...,
        balancer_shares_reward_discount: builtins.str = ...,
        authorized_uptimes: collections.abc.Iterable[google.protobuf.duration_pb2.Duration] | None = ...,
        is_permissionless_pool_creation_enabled: builtins.bool = ...,
        unrestricted_pool_creator_whitelist: collections.abc.Iterable[builtins.str] | None = ...,
        hook_gas_limit: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["authorized_spread_factors", b"authorized_spread_factors", "authorized_tick_spacing", b"authorized_tick_spacing", "authorized_uptimes", b"authorized_uptimes", "balancer_shares_reward_discount", b"balancer_shares_reward_discount", "hook_gas_limit", b"hook_gas_limit", "is_permissionless_pool_creation_enabled", b"is_permissionless_pool_creation_enabled", "unrestricted_pool_creator_whitelist", b"unrestricted_pool_creator_whitelist"]) -> None: ...

global___Params = Params
