"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import cosmos.base.query.v1beta1.pagination_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import stride.epochs.genesis_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryEpochsInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: builtins.int
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: cosmos.base.query.v1beta1.pagination_pb2.PageRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["pagination", b"pagination"]) -> None: ...

global___QueryEpochsInfoRequest = QueryEpochsInfoRequest

@typing.final
class QueryEpochsInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EPOCHS_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    @property
    def epochs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.epochs.genesis_pb2.EpochInfo]: ...
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        epochs: collections.abc.Iterable[stride.epochs.genesis_pb2.EpochInfo] | None = ...,
        pagination: cosmos.base.query.v1beta1.pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["epochs", b"epochs", "pagination", b"pagination"]) -> None: ...

global___QueryEpochsInfoResponse = QueryEpochsInfoResponse

@typing.final
class QueryCurrentEpochRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["identifier", b"identifier"]) -> None: ...

global___QueryCurrentEpochRequest = QueryCurrentEpochRequest

@typing.final
class QueryCurrentEpochResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENT_EPOCH_FIELD_NUMBER: builtins.int
    current_epoch: builtins.int
    def __init__(
        self,
        *,
        current_epoch: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["current_epoch", b"current_epoch"]) -> None: ...

global___QueryCurrentEpochResponse = QueryCurrentEpochResponse

@typing.final
class QueryEpochInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["identifier", b"identifier"]) -> None: ...

global___QueryEpochInfoRequest = QueryEpochInfoRequest

@typing.final
class QueryEpochInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EPOCH_FIELD_NUMBER: builtins.int
    @property
    def epoch(self) -> stride.epochs.genesis_pb2.EpochInfo: ...
    def __init__(
        self,
        *,
        epoch: stride.epochs.genesis_pb2.EpochInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["epoch", b"epoch"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["epoch", b"epoch"]) -> None: ...

global___QueryEpochInfoResponse = QueryEpochInfoResponse
