"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dydxprotocol.bridge.bridge_event_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AddBridgeEventsRequest(google.protobuf.message.Message):
    """AddBridgeEventsRequest is a request message that contains a list of new
    bridge events. The events should be contiguous and sorted by (unique) id.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BRIDGE_EVENTS_FIELD_NUMBER: builtins.int
    @property
    def bridge_events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.bridge.bridge_event_pb2.BridgeEvent]: ...
    def __init__(
        self,
        *,
        bridge_events: collections.abc.Iterable[dydxprotocol.bridge.bridge_event_pb2.BridgeEvent] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bridge_events", b"bridge_events"]) -> None: ...

global___AddBridgeEventsRequest = AddBridgeEventsRequest

@typing.final
class AddBridgeEventsResponse(google.protobuf.message.Message):
    """AddBridgeEventsResponse is a response message for BridgeEventRequest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AddBridgeEventsResponse = AddBridgeEventsResponse
