"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RewardShare(google.protobuf.message.Message):
    """RewardShare stores the relative weight of rewards that each address is
    entitled to.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    WEIGHT_FIELD_NUMBER: builtins.int
    address: builtins.str
    weight: builtins.bytes
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        weight: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "weight", b"weight"]) -> None: ...

global___RewardShare = RewardShare
