# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/records/genesis.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from stride.records import params_pb2 as stride_dot_records_dot_params__pb2
from stride.records import records_pb2 as stride_dot_records_dot_records__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cstride/records/genesis.proto\x12\x0estride.records\x1a\x1bstride/records/params.proto\x1a\x1cstride/records/records.proto\x1a\x14gogoproto/gogo.proto"\xbc\x03\n\x0cGenesisState\x12,\n\x06params\x18\x01 \x01(\x0b\x32\x16.stride.records.ParamsB\x04\xc8\xde\x1f\x00\x12\x0f\n\x07port_id\x18\x02 \x01(\t\x12O\n\x1buser_redemption_record_list\x18\x03 \x03(\x0b\x32$.stride.records.UserRedemptionRecordB\x04\xc8\xde\x1f\x00\x12$\n\x1cuser_redemption_record_count\x18\x04 \x01(\x04\x12O\n\x1b\x65poch_unbonding_record_list\x18\x05 \x03(\x0b\x32$.stride.records.EpochUnbondingRecordB\x04\xc8\xde\x1f\x00\x12@\n\x13\x64\x65posit_record_list\x18\x07 \x03(\x0b\x32\x1d.stride.records.DepositRecordB\x04\xc8\xde\x1f\x00\x12\x1c\n\x14\x64\x65posit_record_count\x18\x08 \x01(\x04\x12\x45\n\x16lsm_token_deposit_list\x18\t \x03(\x0b\x32\x1f.stride.records.LSMTokenDepositB\x04\xc8\xde\x1f\x00\x42\x33Z1github.com/Stride-Labs/stride/v24/x/records/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.records.genesis_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z1github.com/Stride-Labs/stride/v24/x/records/types"
    )
    _globals["_GENESISSTATE"].fields_by_name["params"]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "params"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_GENESISSTATE"].fields_by_name[
        "user_redemption_record_list"
    ]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "user_redemption_record_list"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_GENESISSTATE"].fields_by_name[
        "epoch_unbonding_record_list"
    ]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "epoch_unbonding_record_list"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_GENESISSTATE"].fields_by_name[
        "deposit_record_list"
    ]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "deposit_record_list"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_GENESISSTATE"].fields_by_name[
        "lsm_token_deposit_list"
    ]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "lsm_token_deposit_list"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_GENESISSTATE"]._serialized_start = 130
    _globals["_GENESISSTATE"]._serialized_end = 574
# @@protoc_insertion_point(module_scope)
