"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import cosmos.base.v1beta1.coin_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserRedemptionRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    RECEIVER_FIELD_NUMBER: builtins.int
    NATIVE_TOKEN_AMOUNT_FIELD_NUMBER: builtins.int
    DENOM_FIELD_NUMBER: builtins.int
    HOST_ZONE_ID_FIELD_NUMBER: builtins.int
    EPOCH_NUMBER_FIELD_NUMBER: builtins.int
    CLAIM_IS_PENDING_FIELD_NUMBER: builtins.int
    ST_TOKEN_AMOUNT_FIELD_NUMBER: builtins.int
    id: builtins.str
    """{chain_id}.{epoch}.{receiver}"""
    receiver: builtins.str
    native_token_amount: builtins.str
    denom: builtins.str
    host_zone_id: builtins.str
    epoch_number: builtins.int
    claim_is_pending: builtins.bool
    st_token_amount: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        receiver: builtins.str = ...,
        native_token_amount: builtins.str = ...,
        denom: builtins.str = ...,
        host_zone_id: builtins.str = ...,
        epoch_number: builtins.int = ...,
        claim_is_pending: builtins.bool = ...,
        st_token_amount: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["claim_is_pending", b"claim_is_pending", "denom", b"denom", "epoch_number", b"epoch_number", "host_zone_id", b"host_zone_id", "id", b"id", "native_token_amount", b"native_token_amount", "receiver", b"receiver", "st_token_amount", b"st_token_amount"]) -> None: ...

global___UserRedemptionRecord = UserRedemptionRecord

@typing.final
class DepositRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DepositRecord._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TRANSFER_QUEUE: DepositRecord._Status.ValueType  # 0
        """in transfer queue to be sent to the delegation ICA"""
        TRANSFER_IN_PROGRESS: DepositRecord._Status.ValueType  # 2
        """transfer in progress (IBC packet sent, ack not received)"""
        DELEGATION_QUEUE: DepositRecord._Status.ValueType  # 1
        """in staking queue on delegation ICA"""
        DELEGATION_IN_PROGRESS: DepositRecord._Status.ValueType  # 3
        """staking in progress (ICA packet sent, ack not received)"""

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    TRANSFER_QUEUE: DepositRecord.Status.ValueType  # 0
    """in transfer queue to be sent to the delegation ICA"""
    TRANSFER_IN_PROGRESS: DepositRecord.Status.ValueType  # 2
    """transfer in progress (IBC packet sent, ack not received)"""
    DELEGATION_QUEUE: DepositRecord.Status.ValueType  # 1
    """in staking queue on delegation ICA"""
    DELEGATION_IN_PROGRESS: DepositRecord.Status.ValueType  # 3
    """staking in progress (ICA packet sent, ack not received)"""

    class _Source:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DepositRecord._Source.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRIDE: DepositRecord._Source.ValueType  # 0
        WITHDRAWAL_ICA: DepositRecord._Source.ValueType  # 1

    class Source(_Source, metaclass=_SourceEnumTypeWrapper): ...
    STRIDE: DepositRecord.Source.ValueType  # 0
    WITHDRAWAL_ICA: DepositRecord.Source.ValueType  # 1

    ID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    DENOM_FIELD_NUMBER: builtins.int
    HOST_ZONE_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DEPOSIT_EPOCH_NUMBER_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    DELEGATION_TXS_IN_PROGRESS_FIELD_NUMBER: builtins.int
    id: builtins.int
    amount: builtins.str
    denom: builtins.str
    host_zone_id: builtins.str
    status: global___DepositRecord.Status.ValueType
    deposit_epoch_number: builtins.int
    source: global___DepositRecord.Source.ValueType
    delegation_txs_in_progress: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        amount: builtins.str = ...,
        denom: builtins.str = ...,
        host_zone_id: builtins.str = ...,
        status: global___DepositRecord.Status.ValueType = ...,
        deposit_epoch_number: builtins.int = ...,
        source: global___DepositRecord.Source.ValueType = ...,
        delegation_txs_in_progress: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "delegation_txs_in_progress", b"delegation_txs_in_progress", "denom", b"denom", "deposit_epoch_number", b"deposit_epoch_number", "host_zone_id", b"host_zone_id", "id", b"id", "source", b"source", "status", b"status"]) -> None: ...

global___DepositRecord = DepositRecord

@typing.final
class HostZoneUnbonding(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[HostZoneUnbonding._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNBONDING_QUEUE: HostZoneUnbonding._Status.ValueType  # 0
        """tokens bonded on delegate account"""
        UNBONDING_IN_PROGRESS: HostZoneUnbonding._Status.ValueType  # 3
        """unbonding ICA has been submitted"""
        UNBONDING_RETRY_QUEUE: HostZoneUnbonding._Status.ValueType  # 5
        """unbonding ICA failed for at least one batch and need to be retried"""
        EXIT_TRANSFER_QUEUE: HostZoneUnbonding._Status.ValueType  # 1
        """unbonding completed on delegate account"""
        EXIT_TRANSFER_IN_PROGRESS: HostZoneUnbonding._Status.ValueType  # 4
        """redemption sweep has been submitted"""
        CLAIMABLE: HostZoneUnbonding._Status.ValueType  # 2
        """transfer success"""

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    UNBONDING_QUEUE: HostZoneUnbonding.Status.ValueType  # 0
    """tokens bonded on delegate account"""
    UNBONDING_IN_PROGRESS: HostZoneUnbonding.Status.ValueType  # 3
    """unbonding ICA has been submitted"""
    UNBONDING_RETRY_QUEUE: HostZoneUnbonding.Status.ValueType  # 5
    """unbonding ICA failed for at least one batch and need to be retried"""
    EXIT_TRANSFER_QUEUE: HostZoneUnbonding.Status.ValueType  # 1
    """unbonding completed on delegate account"""
    EXIT_TRANSFER_IN_PROGRESS: HostZoneUnbonding.Status.ValueType  # 4
    """redemption sweep has been submitted"""
    CLAIMABLE: HostZoneUnbonding.Status.ValueType  # 2
    """transfer success"""

    ST_TOKEN_AMOUNT_FIELD_NUMBER: builtins.int
    NATIVE_TOKEN_AMOUNT_FIELD_NUMBER: builtins.int
    ST_TOKENS_TO_BURN_FIELD_NUMBER: builtins.int
    NATIVE_TOKENS_TO_UNBOND_FIELD_NUMBER: builtins.int
    CLAIMABLE_NATIVE_TOKENS_FIELD_NUMBER: builtins.int
    UNDELEGATION_TXS_IN_PROGRESS_FIELD_NUMBER: builtins.int
    DENOM_FIELD_NUMBER: builtins.int
    HOST_ZONE_ID_FIELD_NUMBER: builtins.int
    UNBONDING_TIME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    USER_REDEMPTION_RECORDS_FIELD_NUMBER: builtins.int
    st_token_amount: builtins.str
    native_token_amount: builtins.str
    st_tokens_to_burn: builtins.str
    native_tokens_to_unbond: builtins.str
    claimable_native_tokens: builtins.str
    undelegation_txs_in_progress: builtins.int
    denom: builtins.str
    host_zone_id: builtins.str
    unbonding_time: builtins.int
    status: global___HostZoneUnbonding.Status.ValueType
    @property
    def user_redemption_records(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        st_token_amount: builtins.str = ...,
        native_token_amount: builtins.str = ...,
        st_tokens_to_burn: builtins.str = ...,
        native_tokens_to_unbond: builtins.str = ...,
        claimable_native_tokens: builtins.str = ...,
        undelegation_txs_in_progress: builtins.int = ...,
        denom: builtins.str = ...,
        host_zone_id: builtins.str = ...,
        unbonding_time: builtins.int = ...,
        status: global___HostZoneUnbonding.Status.ValueType = ...,
        user_redemption_records: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["claimable_native_tokens", b"claimable_native_tokens", "denom", b"denom", "host_zone_id", b"host_zone_id", "native_token_amount", b"native_token_amount", "native_tokens_to_unbond", b"native_tokens_to_unbond", "st_token_amount", b"st_token_amount", "st_tokens_to_burn", b"st_tokens_to_burn", "status", b"status", "unbonding_time", b"unbonding_time", "undelegation_txs_in_progress", b"undelegation_txs_in_progress", "user_redemption_records", b"user_redemption_records"]) -> None: ...

global___HostZoneUnbonding = HostZoneUnbonding

@typing.final
class EpochUnbondingRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EPOCH_NUMBER_FIELD_NUMBER: builtins.int
    HOST_ZONE_UNBONDINGS_FIELD_NUMBER: builtins.int
    epoch_number: builtins.int
    @property
    def host_zone_unbondings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HostZoneUnbonding]: ...
    def __init__(
        self,
        *,
        epoch_number: builtins.int = ...,
        host_zone_unbondings: collections.abc.Iterable[global___HostZoneUnbonding] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["epoch_number", b"epoch_number", "host_zone_unbondings", b"host_zone_unbondings"]) -> None: ...

global___EpochUnbondingRecord = EpochUnbondingRecord

@typing.final
class LSMTokenDeposit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LSMTokenDeposit._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DEPOSIT_PENDING: LSMTokenDeposit._Status.ValueType  # 0
        TRANSFER_QUEUE: LSMTokenDeposit._Status.ValueType  # 1
        TRANSFER_IN_PROGRESS: LSMTokenDeposit._Status.ValueType  # 2
        TRANSFER_FAILED: LSMTokenDeposit._Status.ValueType  # 3
        DETOKENIZATION_QUEUE: LSMTokenDeposit._Status.ValueType  # 4
        DETOKENIZATION_IN_PROGRESS: LSMTokenDeposit._Status.ValueType  # 5
        DETOKENIZATION_FAILED: LSMTokenDeposit._Status.ValueType  # 6

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    DEPOSIT_PENDING: LSMTokenDeposit.Status.ValueType  # 0
    TRANSFER_QUEUE: LSMTokenDeposit.Status.ValueType  # 1
    TRANSFER_IN_PROGRESS: LSMTokenDeposit.Status.ValueType  # 2
    TRANSFER_FAILED: LSMTokenDeposit.Status.ValueType  # 3
    DETOKENIZATION_QUEUE: LSMTokenDeposit.Status.ValueType  # 4
    DETOKENIZATION_IN_PROGRESS: LSMTokenDeposit.Status.ValueType  # 5
    DETOKENIZATION_FAILED: LSMTokenDeposit.Status.ValueType  # 6

    DEPOSIT_ID_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    DENOM_FIELD_NUMBER: builtins.int
    IBC_DENOM_FIELD_NUMBER: builtins.int
    STAKER_ADDRESS_FIELD_NUMBER: builtins.int
    VALIDATOR_ADDRESS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    ST_TOKEN_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    deposit_id: builtins.str
    chain_id: builtins.str
    denom: builtins.str
    ibc_denom: builtins.str
    staker_address: builtins.str
    validator_address: builtins.str
    amount: builtins.str
    status: global___LSMTokenDeposit.Status.ValueType
    @property
    def st_token(self) -> cosmos.base.v1beta1.coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        deposit_id: builtins.str = ...,
        chain_id: builtins.str = ...,
        denom: builtins.str = ...,
        ibc_denom: builtins.str = ...,
        staker_address: builtins.str = ...,
        validator_address: builtins.str = ...,
        amount: builtins.str = ...,
        st_token: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
        status: global___LSMTokenDeposit.Status.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["st_token", b"st_token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "chain_id", b"chain_id", "denom", b"denom", "deposit_id", b"deposit_id", "ibc_denom", b"ibc_denom", "st_token", b"st_token", "staker_address", b"staker_address", "status", b"status", "validator_address", b"validator_address"]) -> None: ...

global___LSMTokenDeposit = LSMTokenDeposit
