# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/icacallbacks/params.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 1, "", "stride/icacallbacks/params.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n stride/icacallbacks/params.proto\x12\x13stride.icacallbacks\x1a\x14gogoproto/gogo.proto"\x0e\n\x06Params:\x04\x98\xa0\x1f\x00\x42\x38Z6github.com/Stride-Labs/stride/v24/x/icacallbacks/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.icacallbacks.params_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z6github.com/Stride-Labs/stride/v24/x/icacallbacks/types"
    )
    _globals["_PARAMS"]._loaded_options = None
    _globals["_PARAMS"]._serialized_options = b"\230\240\037\000"
    _globals["_PARAMS"]._serialized_start = 79
    _globals["_PARAMS"]._serialized_end = 93
# @@protoc_insertion_point(module_scope)
