"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import cosmos.base.query.v1beta1.pagination_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import stride.icacallbacks.callback_data_pb2
import stride.icacallbacks.params_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryParamsRequest(google.protobuf.message.Message):
    """QueryParamsRequest is request type for the Query/Params RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryParamsRequest = QueryParamsRequest

@typing.final
class QueryParamsResponse(google.protobuf.message.Message):
    """QueryParamsResponse is response type for the Query/Params RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAMS_FIELD_NUMBER: builtins.int
    @property
    def params(self) -> stride.icacallbacks.params_pb2.Params:
        """params holds all the parameters of this module."""

    def __init__(
        self,
        *,
        params: stride.icacallbacks.params_pb2.Params | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["params", b"params"]) -> None: ...

global___QueryParamsResponse = QueryParamsResponse

@typing.final
class QueryGetCallbackDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALLBACK_KEY_FIELD_NUMBER: builtins.int
    callback_key: builtins.str
    def __init__(
        self,
        *,
        callback_key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["callback_key", b"callback_key"]) -> None: ...

global___QueryGetCallbackDataRequest = QueryGetCallbackDataRequest

@typing.final
class QueryGetCallbackDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALLBACK_DATA_FIELD_NUMBER: builtins.int
    @property
    def callback_data(self) -> stride.icacallbacks.callback_data_pb2.CallbackData: ...
    def __init__(
        self,
        *,
        callback_data: stride.icacallbacks.callback_data_pb2.CallbackData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["callback_data", b"callback_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["callback_data", b"callback_data"]) -> None: ...

global___QueryGetCallbackDataResponse = QueryGetCallbackDataResponse

@typing.final
class QueryAllCallbackDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: builtins.int
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: cosmos.base.query.v1beta1.pagination_pb2.PageRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["pagination", b"pagination"]) -> None: ...

global___QueryAllCallbackDataRequest = QueryAllCallbackDataRequest

@typing.final
class QueryAllCallbackDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALLBACK_DATA_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    @property
    def callback_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.icacallbacks.callback_data_pb2.CallbackData]: ...
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        callback_data: collections.abc.Iterable[stride.icacallbacks.callback_data_pb2.CallbackData] | None = ...,
        pagination: cosmos.base.query.v1beta1.pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["callback_data", b"callback_data", "pagination", b"pagination"]) -> None: ...

global___QueryAllCallbackDataResponse = QueryAllCallbackDataResponse
