# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/icacallbacks/query.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import (
    pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2,
)
from stride.icacallbacks import params_pb2 as stride_dot_icacallbacks_dot_params__pb2
from stride.icacallbacks import (
    callback_data_pb2 as stride_dot_icacallbacks_dot_callback__data__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fstride/icacallbacks/query.proto\x12\x13stride.icacallbacks\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a stride/icacallbacks/params.proto\x1a\'stride/icacallbacks/callback_data.proto"\x14\n\x12QueryParamsRequest"H\n\x13QueryParamsResponse\x12\x31\n\x06params\x18\x01 \x01(\x0b\x32\x1b.stride.icacallbacks.ParamsB\x04\xc8\xde\x1f\x00"3\n\x1bQueryGetCallbackDataRequest\x12\x14\n\x0c\x63\x61llback_key\x18\x01 \x01(\t"^\n\x1cQueryGetCallbackDataResponse\x12>\n\rcallback_data\x18\x01 \x01(\x0b\x32!.stride.icacallbacks.CallbackDataB\x04\xc8\xde\x1f\x00"Y\n\x1bQueryAllCallbackDataRequest\x12:\n\npagination\x18\x01 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest"\x9b\x01\n\x1cQueryAllCallbackDataResponse\x12>\n\rcallback_data\x18\x01 \x03(\x0b\x32!.stride.icacallbacks.CallbackDataB\x04\xc8\xde\x1f\x00\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse2\x84\x04\n\x05Query\x12\x8c\x01\n\x06Params\x12\'.stride.icacallbacks.QueryParamsRequest\x1a(.stride.icacallbacks.QueryParamsResponse"/\x82\xd3\xe4\x93\x02)\x12\'/Stride-Labs/stride/icacallbacks/params\x12\xba\x01\n\x0c\x43\x61llbackData\x12\x30.stride.icacallbacks.QueryGetCallbackDataRequest\x1a\x31.stride.icacallbacks.QueryGetCallbackDataResponse"E\x82\xd3\xe4\x93\x02?\x12=/Stride-Labs/stride/icacallbacks/callback_data/{callback_key}\x12\xae\x01\n\x0f\x43\x61llbackDataAll\x12\x30.stride.icacallbacks.QueryAllCallbackDataRequest\x1a\x31.stride.icacallbacks.QueryAllCallbackDataResponse"6\x82\xd3\xe4\x93\x02\x30\x12./Stride-Labs/stride/icacallbacks/callback_dataB8Z6github.com/Stride-Labs/stride/v24/x/icacallbacks/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.icacallbacks.query_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z6github.com/Stride-Labs/stride/v24/x/icacallbacks/types"
    )
    _globals["_QUERYPARAMSRESPONSE"].fields_by_name["params"]._loaded_options = None
    _globals["_QUERYPARAMSRESPONSE"].fields_by_name[
        "params"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_QUERYGETCALLBACKDATARESPONSE"].fields_by_name[
        "callback_data"
    ]._loaded_options = None
    _globals["_QUERYGETCALLBACKDATARESPONSE"].fields_by_name[
        "callback_data"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_QUERYALLCALLBACKDATARESPONSE"].fields_by_name[
        "callback_data"
    ]._loaded_options = None
    _globals["_QUERYALLCALLBACKDATARESPONSE"].fields_by_name[
        "callback_data"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_QUERY"].methods_by_name["Params"]._loaded_options = None
    _globals["_QUERY"].methods_by_name[
        "Params"
    ]._serialized_options = (
        b"\202\323\344\223\002)\022'/Stride-Labs/stride/icacallbacks/params"
    )
    _globals["_QUERY"].methods_by_name["CallbackData"]._loaded_options = None
    _globals["_QUERY"].methods_by_name[
        "CallbackData"
    ]._serialized_options = b"\202\323\344\223\002?\022=/Stride-Labs/stride/icacallbacks/callback_data/{callback_key}"
    _globals["_QUERY"].methods_by_name["CallbackDataAll"]._loaded_options = None
    _globals["_QUERY"].methods_by_name[
        "CallbackDataAll"
    ]._serialized_options = (
        b"\202\323\344\223\0020\022./Stride-Labs/stride/icacallbacks/callback_data"
    )
    _globals["_QUERYPARAMSREQUEST"]._serialized_start = 227
    _globals["_QUERYPARAMSREQUEST"]._serialized_end = 247
    _globals["_QUERYPARAMSRESPONSE"]._serialized_start = 249
    _globals["_QUERYPARAMSRESPONSE"]._serialized_end = 321
    _globals["_QUERYGETCALLBACKDATAREQUEST"]._serialized_start = 323
    _globals["_QUERYGETCALLBACKDATAREQUEST"]._serialized_end = 374
    _globals["_QUERYGETCALLBACKDATARESPONSE"]._serialized_start = 376
    _globals["_QUERYGETCALLBACKDATARESPONSE"]._serialized_end = 470
    _globals["_QUERYALLCALLBACKDATAREQUEST"]._serialized_start = 472
    _globals["_QUERYALLCALLBACKDATAREQUEST"]._serialized_end = 561
    _globals["_QUERYALLCALLBACKDATARESPONSE"]._serialized_start = 564
    _globals["_QUERYALLCALLBACKDATARESPONSE"]._serialized_end = 719
    _globals["_QUERY"]._serialized_start = 722
    _globals["_QUERY"]._serialized_end = 1238
# @@protoc_insertion_point(module_scope)
