"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.vest.vest_entry_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryVestEntryRequest(google.protobuf.message.Message):
    """QueryVestEntryRequest is a request type for the VestEntry RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VESTER_ACCOUNT_FIELD_NUMBER: builtins.int
    vester_account: builtins.str
    def __init__(
        self,
        *,
        vester_account: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vester_account", b"vester_account"]) -> None: ...

global___QueryVestEntryRequest = QueryVestEntryRequest

@typing.final
class QueryVestEntryResponse(google.protobuf.message.Message):
    """QueryVestEntryResponse is a response type for the VestEntry RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRY_FIELD_NUMBER: builtins.int
    @property
    def entry(self) -> dydxprotocol.vest.vest_entry_pb2.VestEntry: ...
    def __init__(
        self,
        *,
        entry: dydxprotocol.vest.vest_entry_pb2.VestEntry | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["entry", b"entry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["entry", b"entry"]) -> None: ...

global___QueryVestEntryResponse = QueryVestEntryResponse
