"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class VestEntry(google.protobuf.message.Message):
    """VestEntry specifies a Vester Account and the rate at which tokens are
    dripped into the corresponding Treasury Account.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VESTER_ACCOUNT_FIELD_NUMBER: builtins.int
    TREASURY_ACCOUNT_FIELD_NUMBER: builtins.int
    DENOM_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    vester_account: builtins.str
    """The module account to vest tokens from.
    This is also the key to this `VestEntry` in state.
    """
    treasury_account: builtins.str
    """The module account to vest tokens to."""
    denom: builtins.str
    """The denom of the token to vest."""
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The start time of vest. Before this time, no vest will occur."""

    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The end time of vest. At this target date, all funds should be in the
        Treasury Account and none left in the Vester Account.
        """

    def __init__(
        self,
        *,
        vester_account: builtins.str = ...,
        treasury_account: builtins.str = ...,
        denom: builtins.str = ...,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_time", b"end_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["denom", b"denom", "end_time", b"end_time", "start_time", b"start_time", "treasury_account", b"treasury_account", "vester_account", b"vester_account"]) -> None: ...

global___VestEntry = VestEntry
