"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dydxprotocol.vault.params_pb2
import dydxprotocol.vault.share_pb2
import dydxprotocol.vault.vault_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines `x/vault`'s genesis state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_SHARES_FIELD_NUMBER: builtins.int
    OWNER_SHARES_FIELD_NUMBER: builtins.int
    VAULTS_FIELD_NUMBER: builtins.int
    DEFAULT_QUOTING_PARAMS_FIELD_NUMBER: builtins.int
    ALL_OWNER_SHARE_UNLOCKS_FIELD_NUMBER: builtins.int
    OPERATOR_PARAMS_FIELD_NUMBER: builtins.int
    @property
    def total_shares(self) -> dydxprotocol.vault.share_pb2.NumShares:
        """The total number of shares, including any locked ones."""

    @property
    def owner_shares(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.vault.share_pb2.OwnerShare]:
        """The shares of each owner, including any locked ones."""

    @property
    def vaults(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Vault]:
        """The vaults."""

    @property
    def default_quoting_params(self) -> dydxprotocol.vault.params_pb2.QuotingParams:
        """The default quoting parameters for all vaults."""

    @property
    def all_owner_share_unlocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.vault.share_pb2.OwnerShareUnlocks]:
        """All owner share unlocks."""

    @property
    def operator_params(self) -> dydxprotocol.vault.params_pb2.OperatorParams:
        """The parameters regarding megavault operator."""

    def __init__(
        self,
        *,
        total_shares: dydxprotocol.vault.share_pb2.NumShares | None = ...,
        owner_shares: collections.abc.Iterable[dydxprotocol.vault.share_pb2.OwnerShare] | None = ...,
        vaults: collections.abc.Iterable[global___Vault] | None = ...,
        default_quoting_params: dydxprotocol.vault.params_pb2.QuotingParams | None = ...,
        all_owner_share_unlocks: collections.abc.Iterable[dydxprotocol.vault.share_pb2.OwnerShareUnlocks] | None = ...,
        operator_params: dydxprotocol.vault.params_pb2.OperatorParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["default_quoting_params", b"default_quoting_params", "operator_params", b"operator_params", "total_shares", b"total_shares"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["all_owner_share_unlocks", b"all_owner_share_unlocks", "default_quoting_params", b"default_quoting_params", "operator_params", b"operator_params", "owner_shares", b"owner_shares", "total_shares", b"total_shares", "vaults", b"vaults"]) -> None: ...

global___GenesisState = GenesisState

@typing.final
class Vault(google.protobuf.message.Message):
    """Vault defines the state of a vault."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VAULT_ID_FIELD_NUMBER: builtins.int
    VAULT_PARAMS_FIELD_NUMBER: builtins.int
    MOST_RECENT_CLIENT_IDS_FIELD_NUMBER: builtins.int
    @property
    def vault_id(self) -> dydxprotocol.vault.vault_pb2.VaultId:
        """The ID of the vault."""

    @property
    def vault_params(self) -> dydxprotocol.vault.params_pb2.VaultParams:
        """The parameters of the vault."""

    @property
    def most_recent_client_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """The client IDs of the most recently placed orders of the vault."""

    def __init__(
        self,
        *,
        vault_id: dydxprotocol.vault.vault_pb2.VaultId | None = ...,
        vault_params: dydxprotocol.vault.params_pb2.VaultParams | None = ...,
        most_recent_client_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["vault_id", b"vault_id", "vault_params", b"vault_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["most_recent_client_ids", b"most_recent_client_ids", "vault_id", b"vault_id", "vault_params", b"vault_params"]) -> None: ...

global___Vault = Vault

@typing.final
class GenesisStateV6(google.protobuf.message.Message):
    """GenesisStateV6 defines `x/vault`'s genesis state in v6.x.
    Deprecated since v7.x in favor of GenesisState.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VAULTS_FIELD_NUMBER: builtins.int
    DEFAULT_QUOTING_PARAMS_FIELD_NUMBER: builtins.int
    @property
    def vaults(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Vault]:
        """The vaults."""

    @property
    def default_quoting_params(self) -> dydxprotocol.vault.params_pb2.QuotingParams:
        """The default quoting parameters for all vaults."""

    def __init__(
        self,
        *,
        vaults: collections.abc.Iterable[global___Vault] | None = ...,
        default_quoting_params: dydxprotocol.vault.params_pb2.QuotingParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["default_quoting_params", b"default_quoting_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["default_quoting_params", b"default_quoting_params", "vaults", b"vaults"]) -> None: ...

global___GenesisStateV6 = GenesisStateV6

@typing.final
class VaultV6(google.protobuf.message.Message):
    """VaultV6 defines the state of a vault.
    Deprecated since v7.x in favor of Vault.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VAULT_ID_FIELD_NUMBER: builtins.int
    TOTAL_SHARES_FIELD_NUMBER: builtins.int
    OWNER_SHARES_FIELD_NUMBER: builtins.int
    VAULT_PARAMS_FIELD_NUMBER: builtins.int
    MOST_RECENT_CLIENT_IDS_FIELD_NUMBER: builtins.int
    @property
    def vault_id(self) -> dydxprotocol.vault.vault_pb2.VaultId:
        """The ID of the vault."""

    @property
    def total_shares(self) -> dydxprotocol.vault.share_pb2.NumShares:
        """The total number of shares in the vault."""

    @property
    def owner_shares(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.vault.share_pb2.OwnerShare]:
        """The shares of each owner in the vault."""

    @property
    def vault_params(self) -> dydxprotocol.vault.params_pb2.VaultParams:
        """The parameters of the vault."""

    @property
    def most_recent_client_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """The client IDs of the most recently placed orders of the vault."""

    def __init__(
        self,
        *,
        vault_id: dydxprotocol.vault.vault_pb2.VaultId | None = ...,
        total_shares: dydxprotocol.vault.share_pb2.NumShares | None = ...,
        owner_shares: collections.abc.Iterable[dydxprotocol.vault.share_pb2.OwnerShare] | None = ...,
        vault_params: dydxprotocol.vault.params_pb2.VaultParams | None = ...,
        most_recent_client_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["total_shares", b"total_shares", "vault_id", b"vault_id", "vault_params", b"vault_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["most_recent_client_ids", b"most_recent_client_ids", "owner_shares", b"owner_shares", "total_shares", b"total_shares", "vault_id", b"vault_id", "vault_params", b"vault_params"]) -> None: ...

global___VaultV6 = VaultV6
