"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dydxprotocol.ratelimit.capacity_pb2
import dydxprotocol.ratelimit.limit_params_pb2
import dydxprotocol.ratelimit.pending_send_packet_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ListLimitParamsRequest(google.protobuf.message.Message):
    """ListLimitParamsRequest is a request type of the ListLimitParams RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListLimitParamsRequest = ListLimitParamsRequest

@typing.final
class ListLimitParamsResponse(google.protobuf.message.Message):
    """ListLimitParamsResponse is a response type of the ListLimitParams RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIMIT_PARAMS_LIST_FIELD_NUMBER: builtins.int
    @property
    def limit_params_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.ratelimit.limit_params_pb2.LimitParams]: ...
    def __init__(
        self,
        *,
        limit_params_list: collections.abc.Iterable[dydxprotocol.ratelimit.limit_params_pb2.LimitParams] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit_params_list", b"limit_params_list"]) -> None: ...

global___ListLimitParamsResponse = ListLimitParamsResponse

@typing.final
class QueryCapacityByDenomRequest(google.protobuf.message.Message):
    """QueryCapacityByDenomRequest is a request type for the CapacityByDenom RPC
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DENOM_FIELD_NUMBER: builtins.int
    denom: builtins.str
    def __init__(
        self,
        *,
        denom: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["denom", b"denom"]) -> None: ...

global___QueryCapacityByDenomRequest = QueryCapacityByDenomRequest

@typing.final
class QueryCapacityByDenomResponse(google.protobuf.message.Message):
    """QueryCapacityByDenomResponse is a response type of the CapacityByDenom RPC
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIMITER_CAPACITY_LIST_FIELD_NUMBER: builtins.int
    @property
    def limiter_capacity_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.ratelimit.capacity_pb2.LimiterCapacity]: ...
    def __init__(
        self,
        *,
        limiter_capacity_list: collections.abc.Iterable[dydxprotocol.ratelimit.capacity_pb2.LimiterCapacity] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limiter_capacity_list", b"limiter_capacity_list"]) -> None: ...

global___QueryCapacityByDenomResponse = QueryCapacityByDenomResponse

@typing.final
class QueryAllPendingSendPacketsRequest(google.protobuf.message.Message):
    """QueryAllPendingSendPacketsRequest is a request type for the
    AllPendingSendPackets RPC
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryAllPendingSendPacketsRequest = QueryAllPendingSendPacketsRequest

@typing.final
class QueryAllPendingSendPacketsResponse(google.protobuf.message.Message):
    """QueryAllPendingSendPacketsResponse is a response type of the
    AllPendingSendPackets RPC
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PENDING_SEND_PACKETS_FIELD_NUMBER: builtins.int
    @property
    def pending_send_packets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.ratelimit.pending_send_packet_pb2.PendingSendPacket]: ...
    def __init__(
        self,
        *,
        pending_send_packets: collections.abc.Iterable[dydxprotocol.ratelimit.pending_send_packet_pb2.PendingSendPacket] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pending_send_packets", b"pending_send_packets"]) -> None: ...

global___QueryAllPendingSendPacketsResponse = QueryAllPendingSendPacketsResponse
