# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/claim/claim.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18stride/claim/claim.proto\x12\x0cstride.claim\x1a\x14gogoproto/gogo.proto"\xf5\x01\n\x0b\x43laimRecord\x12\x39\n\x12\x61irdrop_identifier\x18\x01 \x01(\tB\x1d\xf2\xde\x1f\x19yaml:"airdrop_identifier"\x12#\n\x07\x61\x64\x64ress\x18\x02 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:"address"\x12O\n\x06weight\x18\x03 \x01(\tB?\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\ryaml:"weight"\x12\x35\n\x10\x61\x63tion_completed\x18\x04 \x03(\x08\x42\x1b\xf2\xde\x1f\x17yaml:"action_completed"*S\n\x06\x41\x63tion\x12\x0f\n\x0b\x41\x43TION_FREE\x10\x00\x12\x17\n\x13\x41\x43TION_LIQUID_STAKE\x10\x01\x12\x19\n\x15\x41\x43TION_DELEGATE_STAKE\x10\x02\x1a\x04\x88\xa3\x1e\x00\x42\x31Z/github.com/Stride-Labs/stride/v24/x/claim/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "stride.claim.claim_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z/github.com/Stride-Labs/stride/v24/x/claim/types"
    )
    _globals["_ACTION"]._loaded_options = None
    _globals["_ACTION"]._serialized_options = b"\210\243\036\000"
    _globals["_CLAIMRECORD"].fields_by_name["airdrop_identifier"]._loaded_options = None
    _globals["_CLAIMRECORD"].fields_by_name[
        "airdrop_identifier"
    ]._serialized_options = b'\362\336\037\031yaml:"airdrop_identifier"'
    _globals["_CLAIMRECORD"].fields_by_name["address"]._loaded_options = None
    _globals["_CLAIMRECORD"].fields_by_name[
        "address"
    ]._serialized_options = b'\362\336\037\016yaml:"address"'
    _globals["_CLAIMRECORD"].fields_by_name["weight"]._loaded_options = None
    _globals["_CLAIMRECORD"].fields_by_name[
        "weight"
    ]._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\ryaml:"weight"'
    _globals["_CLAIMRECORD"].fields_by_name["action_completed"]._loaded_options = None
    _globals["_CLAIMRECORD"].fields_by_name[
        "action_completed"
    ]._serialized_options = b'\362\336\037\027yaml:"action_completed"'
    _globals["_ACTION"]._serialized_start = 312
    _globals["_ACTION"]._serialized_end = 395
    _globals["_CLAIMRECORD"]._serialized_start = 65
    _globals["_CLAIMRECORD"]._serialized_end = 310
# @@protoc_insertion_point(module_scope)
