"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import stride.claim.claim_pb2
import stride.claim.params_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines the claim module's genesis state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAMS_FIELD_NUMBER: builtins.int
    CLAIM_RECORDS_FIELD_NUMBER: builtins.int
    @property
    def params(self) -> stride.claim.params_pb2.Params:
        """params defines all the parameters of the module."""

    @property
    def claim_records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.claim.claim_pb2.ClaimRecord]:
        """list of claim records, one for every airdrop recipient"""

    def __init__(
        self,
        *,
        params: stride.claim.params_pb2.Params | None = ...,
        claim_records: collections.abc.Iterable[stride.claim.claim_pb2.ClaimRecord] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["claim_records", b"claim_records", "params", b"params"]) -> None: ...

global___GenesisState = GenesisState
