"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Params(google.protobuf.message.Message):
    """Params defines the claim module's parameters."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AIRDROPS_FIELD_NUMBER: builtins.int
    @property
    def airdrops(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Airdrop]: ...
    def __init__(
        self,
        *,
        airdrops: collections.abc.Iterable[global___Airdrop] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["airdrops", b"airdrops"]) -> None: ...

global___Params = Params

@typing.final
class Airdrop(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AIRDROP_IDENTIFIER_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    AIRDROP_START_TIME_FIELD_NUMBER: builtins.int
    AIRDROP_DURATION_FIELD_NUMBER: builtins.int
    CLAIM_DENOM_FIELD_NUMBER: builtins.int
    DISTRIBUTOR_ADDRESS_FIELD_NUMBER: builtins.int
    CLAIMED_SO_FAR_FIELD_NUMBER: builtins.int
    AUTOPILOT_ENABLED_FIELD_NUMBER: builtins.int
    airdrop_identifier: builtins.str
    chain_id: builtins.str
    claim_denom: builtins.str
    """denom of claimable asset"""
    distributor_address: builtins.str
    """airdrop distribution account"""
    claimed_so_far: builtins.str
    """ustrd tokens claimed so far in the current period"""
    autopilot_enabled: builtins.bool
    """indicates the airdrop should be claimed via autopilot"""
    @property
    def airdrop_start_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """seconds"""

    @property
    def airdrop_duration(self) -> google.protobuf.duration_pb2.Duration:
        """seconds"""

    def __init__(
        self,
        *,
        airdrop_identifier: builtins.str = ...,
        chain_id: builtins.str = ...,
        airdrop_start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        airdrop_duration: google.protobuf.duration_pb2.Duration | None = ...,
        claim_denom: builtins.str = ...,
        distributor_address: builtins.str = ...,
        claimed_so_far: builtins.str = ...,
        autopilot_enabled: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["airdrop_duration", b"airdrop_duration", "airdrop_start_time", b"airdrop_start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["airdrop_duration", b"airdrop_duration", "airdrop_identifier", b"airdrop_identifier", "airdrop_start_time", b"airdrop_start_time", "autopilot_enabled", b"autopilot_enabled", "chain_id", b"chain_id", "claim_denom", b"claim_denom", "claimed_so_far", b"claimed_so_far", "distributor_address", b"distributor_address"]) -> None: ...

global___Airdrop = Airdrop
