# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osmosis/concentratedliquidity/poolmodel/concentrated/v1beta1/tx.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\nEosmosis/concentratedliquidity/poolmodel/concentrated/v1beta1/tx.proto\x12<osmosis.concentratedliquidity.poolmodel.concentrated.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x11\x61mino/amino.proto\x1a\x17\x63osmos/msg/v1/msg.proto\"\xb9\x02\n\x19MsgCreateConcentratedPool\x12!\n\x06sender\x18\x01 \x01(\tB\x11\xf2\xde\x1f\ryaml:\"sender\"\x12!\n\x06\x64\x65nom0\x18\x02 \x01(\tB\x11\xf2\xde\x1f\ryaml:\"denom0\"\x12!\n\x06\x64\x65nom1\x18\x03 \x01(\tB\x11\xf2\xde\x1f\ryaml:\"denom1\"\x12-\n\x0ctick_spacing\x18\x04 \x01(\x04\x42\x17\xf2\xde\x1f\x13yaml:\"tick_spacing\"\x12R\n\rspread_factor\x18\x05 \x01(\tB;\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDec\xf2\xde\x1f\x14yaml:\"spread_factor\":0\x82\xe7\xb0*\x06sender\x8a\xe7\xb0* osmosis/create-concentrated-pool\"@\n!MsgCreateConcentratedPoolResponse\x12\x1b\n\x07pool_id\x18\x01 \x01(\x04\x42\n\xe2\xde\x1f\x06PoolID2\xda\x01\n\x03Msg\x12\xd2\x01\n\x16\x43reateConcentratedPool\x12W.osmosis.concentratedliquidity.poolmodel.concentrated.v1beta1.MsgCreateConcentratedPool\x1a_.osmosis.concentratedliquidity.poolmodel.concentrated.v1beta1.MsgCreateConcentratedPoolResponseBDZBgithub.com/osmosis-labs/osmosis/v25/x/concentrated-liquidity/modelb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'osmosis.concentratedliquidity.poolmodel.concentrated.v1beta1.tx_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/osmosis-labs/osmosis/v25/x/concentrated-liquidity/model'
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name['sender']._loaded_options = None
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name[
        'sender'
    ]._serialized_options = b'\362\336\037\ryaml:\"sender\"'
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name['denom0']._loaded_options = None
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name[
        'denom0'
    ]._serialized_options = b'\362\336\037\ryaml:\"denom0\"'
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name['denom1']._loaded_options = None
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name[
        'denom1'
    ]._serialized_options = b'\362\336\037\ryaml:\"denom1\"'
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name['tick_spacing']._loaded_options = None
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name[
        'tick_spacing'
    ]._serialized_options = b'\362\336\037\023yaml:\"tick_spacing\"'
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name['spread_factor']._loaded_options = None
    _globals['_MSGCREATECONCENTRATEDPOOL'].fields_by_name[
        'spread_factor'
    ]._serialized_options = (
        b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec\362\336\037\024yaml:\"spread_factor\"'
    )
    _globals['_MSGCREATECONCENTRATEDPOOL']._loaded_options = None
    _globals['_MSGCREATECONCENTRATEDPOOL']._serialized_options = (
        b'\202\347\260*\006sender\212\347\260* osmosis/create-concentrated-pool'
    )
    _globals['_MSGCREATECONCENTRATEDPOOLRESPONSE'].fields_by_name['pool_id']._loaded_options = None
    _globals['_MSGCREATECONCENTRATEDPOOLRESPONSE'].fields_by_name[
        'pool_id'
    ]._serialized_options = b'\342\336\037\006PoolID'
    _globals['_MSGCREATECONCENTRATEDPOOL']._serialized_start = 202
    _globals['_MSGCREATECONCENTRATEDPOOL']._serialized_end = 515
    _globals['_MSGCREATECONCENTRATEDPOOLRESPONSE']._serialized_start = 517
    _globals['_MSGCREATECONCENTRATEDPOOLRESPONSE']._serialized_end = 581
    _globals['_MSG']._serialized_start = 584
    _globals['_MSG']._serialized_end = 802
# @@protoc_insertion_point(module_scope)
