"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.clob.query_pb2
import dydxprotocol.prices.streaming_pb2
import dydxprotocol.subaccounts.streaming_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StagedFinalizeBlockEvent(google.protobuf.message.Message):
    """StagedFinalizeBlockEvent is an event staged during `FinalizeBlock`."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_FILL_FIELD_NUMBER: builtins.int
    SUBACCOUNT_UPDATE_FIELD_NUMBER: builtins.int
    ORDERBOOK_UPDATE_FIELD_NUMBER: builtins.int
    PRICE_UPDATE_FIELD_NUMBER: builtins.int
    @property
    def order_fill(self) -> dydxprotocol.clob.query_pb2.StreamOrderbookFill: ...
    @property
    def subaccount_update(self) -> dydxprotocol.subaccounts.streaming_pb2.StreamSubaccountUpdate: ...
    @property
    def orderbook_update(self) -> dydxprotocol.clob.query_pb2.StreamOrderbookUpdate: ...
    @property
    def price_update(self) -> dydxprotocol.prices.streaming_pb2.StreamPriceUpdate: ...
    def __init__(
        self,
        *,
        order_fill: dydxprotocol.clob.query_pb2.StreamOrderbookFill | None = ...,
        subaccount_update: dydxprotocol.subaccounts.streaming_pb2.StreamSubaccountUpdate | None = ...,
        orderbook_update: dydxprotocol.clob.query_pb2.StreamOrderbookUpdate | None = ...,
        price_update: dydxprotocol.prices.streaming_pb2.StreamPriceUpdate | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["event", b"event", "order_fill", b"order_fill", "orderbook_update", b"orderbook_update", "price_update", b"price_update", "subaccount_update", b"subaccount_update"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["event", b"event", "order_fill", b"order_fill", "orderbook_update", b"orderbook_update", "price_update", b"price_update", "subaccount_update", b"subaccount_update"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["event", b"event"]) -> typing.Literal["order_fill", "subaccount_update", "orderbook_update", "price_update"] | None: ...

global___StagedFinalizeBlockEvent = StagedFinalizeBlockEvent
