"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.affiliates.affiliates_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines generis state of `x/affiliates`"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AFFILIATE_TIERS_FIELD_NUMBER: builtins.int
    @property
    def affiliate_tiers(self) -> dydxprotocol.affiliates.affiliates_pb2.AffiliateTiers:
        """The list of affiliate tiers"""

    def __init__(
        self,
        *,
        affiliate_tiers: dydxprotocol.affiliates.affiliates_pb2.AffiliateTiers | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["affiliate_tiers", b"affiliate_tiers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["affiliate_tiers", b"affiliate_tiers"]) -> None: ...

global___GenesisState = GenesisState
