# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/mint/v1beta1/genesis.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from stride.mint.v1beta1 import mint_pb2 as stride_dot_mint_dot_v1beta1_dot_mint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!stride/mint/v1beta1/genesis.proto\x12\x13stride.mint.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1estride/mint/v1beta1/mint.proto"\xb9\x01\n\x0cGenesisState\x12\x31\n\x06minter\x18\x01 \x01(\x0b\x32\x1b.stride.mint.v1beta1.MinterB\x04\xc8\xde\x1f\x00\x12\x31\n\x06params\x18\x02 \x01(\x0b\x32\x1b.stride.mint.v1beta1.ParamsB\x04\xc8\xde\x1f\x00\x12\x43\n\x17reduction_started_epoch\x18\x03 \x01(\x03\x42"\xf2\xde\x1f\x1eyaml:"reduction_started_epoch"B0Z.github.com/Stride-Labs/stride/v24/x/mint/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.mint.v1beta1.genesis_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z.github.com/Stride-Labs/stride/v24/x/mint/types"
    )
    _globals["_GENESISSTATE"].fields_by_name["minter"]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "minter"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_GENESISSTATE"].fields_by_name["params"]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "params"
    ]._serialized_options = b"\310\336\037\000"
    _globals["_GENESISSTATE"].fields_by_name[
        "reduction_started_epoch"
    ]._loaded_options = None
    _globals["_GENESISSTATE"].fields_by_name[
        "reduction_started_epoch"
    ]._serialized_options = b'\362\336\037\036yaml:"reduction_started_epoch"'
    _globals["_GENESISSTATE"]._serialized_start = 113
    _globals["_GENESISSTATE"]._serialized_end = 298
# @@protoc_insertion_point(module_scope)
