"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import cosmos.base.v1beta1.coin_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import stride.staketia.staketia_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _OverwritableRecordType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OverwritableRecordTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OverwritableRecordType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RECORD_TYPE_DELEGATION: _OverwritableRecordType.ValueType  # 0
    RECORD_TYPE_UNBONDING: _OverwritableRecordType.ValueType  # 1
    RECORD_TYPE_REDEMPTION: _OverwritableRecordType.ValueType  # 2

class OverwritableRecordType(_OverwritableRecordType, metaclass=_OverwritableRecordTypeEnumTypeWrapper): ...

RECORD_TYPE_DELEGATION: OverwritableRecordType.ValueType  # 0
RECORD_TYPE_UNBONDING: OverwritableRecordType.ValueType  # 1
RECORD_TYPE_REDEMPTION: OverwritableRecordType.ValueType  # 2
global___OverwritableRecordType = OverwritableRecordType

@typing.final
class MsgLiquidStake(google.protobuf.message.Message):
    """LiquidStake"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STAKER_FIELD_NUMBER: builtins.int
    NATIVE_AMOUNT_FIELD_NUMBER: builtins.int
    staker: builtins.str
    native_amount: builtins.str
    def __init__(
        self,
        *,
        staker: builtins.str = ...,
        native_amount: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["native_amount", b"native_amount", "staker", b"staker"]) -> None: ...

global___MsgLiquidStake = MsgLiquidStake

@typing.final
class MsgLiquidStakeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ST_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def st_token(self) -> cosmos.base.v1beta1.coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        st_token: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["st_token", b"st_token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["st_token", b"st_token"]) -> None: ...

global___MsgLiquidStakeResponse = MsgLiquidStakeResponse

@typing.final
class MsgRedeemStake(google.protobuf.message.Message):
    """RedeemStake"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REDEEMER_FIELD_NUMBER: builtins.int
    ST_TOKEN_AMOUNT_FIELD_NUMBER: builtins.int
    redeemer: builtins.str
    st_token_amount: builtins.str
    def __init__(
        self,
        *,
        redeemer: builtins.str = ...,
        st_token_amount: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["redeemer", b"redeemer", "st_token_amount", b"st_token_amount"]) -> None: ...

global___MsgRedeemStake = MsgRedeemStake

@typing.final
class MsgRedeemStakeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NATIVE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def native_token(self) -> cosmos.base.v1beta1.coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        native_token: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["native_token", b"native_token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["native_token", b"native_token"]) -> None: ...

global___MsgRedeemStakeResponse = MsgRedeemStakeResponse

@typing.final
class MsgConfirmDelegation(google.protobuf.message.Message):
    """ConfirmDelegation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATOR_FIELD_NUMBER: builtins.int
    RECORD_ID_FIELD_NUMBER: builtins.int
    TX_HASH_FIELD_NUMBER: builtins.int
    operator: builtins.str
    record_id: builtins.int
    tx_hash: builtins.str
    def __init__(
        self,
        *,
        operator: builtins.str = ...,
        record_id: builtins.int = ...,
        tx_hash: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operator", b"operator", "record_id", b"record_id", "tx_hash", b"tx_hash"]) -> None: ...

global___MsgConfirmDelegation = MsgConfirmDelegation

@typing.final
class MsgConfirmDelegationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgConfirmDelegationResponse = MsgConfirmDelegationResponse

@typing.final
class MsgConfirmUndelegation(google.protobuf.message.Message):
    """ConfirmUndelegation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATOR_FIELD_NUMBER: builtins.int
    RECORD_ID_FIELD_NUMBER: builtins.int
    TX_HASH_FIELD_NUMBER: builtins.int
    operator: builtins.str
    record_id: builtins.int
    tx_hash: builtins.str
    def __init__(
        self,
        *,
        operator: builtins.str = ...,
        record_id: builtins.int = ...,
        tx_hash: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operator", b"operator", "record_id", b"record_id", "tx_hash", b"tx_hash"]) -> None: ...

global___MsgConfirmUndelegation = MsgConfirmUndelegation

@typing.final
class MsgConfirmUndelegationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgConfirmUndelegationResponse = MsgConfirmUndelegationResponse

@typing.final
class MsgConfirmUnbondedTokenSweep(google.protobuf.message.Message):
    """ConfirmUnbondedTokenSweep"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATOR_FIELD_NUMBER: builtins.int
    RECORD_ID_FIELD_NUMBER: builtins.int
    TX_HASH_FIELD_NUMBER: builtins.int
    operator: builtins.str
    record_id: builtins.int
    tx_hash: builtins.str
    def __init__(
        self,
        *,
        operator: builtins.str = ...,
        record_id: builtins.int = ...,
        tx_hash: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operator", b"operator", "record_id", b"record_id", "tx_hash", b"tx_hash"]) -> None: ...

global___MsgConfirmUnbondedTokenSweep = MsgConfirmUnbondedTokenSweep

@typing.final
class MsgConfirmUnbondedTokenSweepResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgConfirmUnbondedTokenSweepResponse = MsgConfirmUnbondedTokenSweepResponse

@typing.final
class MsgAdjustDelegatedBalance(google.protobuf.message.Message):
    """AdjustDelegatedBalance"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATOR_FIELD_NUMBER: builtins.int
    DELEGATION_OFFSET_FIELD_NUMBER: builtins.int
    VALIDATOR_ADDRESS_FIELD_NUMBER: builtins.int
    operator: builtins.str
    delegation_offset: builtins.str
    validator_address: builtins.str
    def __init__(
        self,
        *,
        operator: builtins.str = ...,
        delegation_offset: builtins.str = ...,
        validator_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delegation_offset", b"delegation_offset", "operator", b"operator", "validator_address", b"validator_address"]) -> None: ...

global___MsgAdjustDelegatedBalance = MsgAdjustDelegatedBalance

@typing.final
class MsgAdjustDelegatedBalanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgAdjustDelegatedBalanceResponse = MsgAdjustDelegatedBalanceResponse

@typing.final
class MsgUpdateInnerRedemptionRateBounds(google.protobuf.message.Message):
    """UpdateInnerRedemptionRate"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    MIN_INNER_REDEMPTION_RATE_FIELD_NUMBER: builtins.int
    MAX_INNER_REDEMPTION_RATE_FIELD_NUMBER: builtins.int
    creator: builtins.str
    min_inner_redemption_rate: builtins.str
    max_inner_redemption_rate: builtins.str
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        min_inner_redemption_rate: builtins.str = ...,
        max_inner_redemption_rate: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator", "max_inner_redemption_rate", b"max_inner_redemption_rate", "min_inner_redemption_rate", b"min_inner_redemption_rate"]) -> None: ...

global___MsgUpdateInnerRedemptionRateBounds = MsgUpdateInnerRedemptionRateBounds

@typing.final
class MsgUpdateInnerRedemptionRateBoundsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgUpdateInnerRedemptionRateBoundsResponse = MsgUpdateInnerRedemptionRateBoundsResponse

@typing.final
class MsgResumeHostZone(google.protobuf.message.Message):
    """ResumeHostZone"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    creator: builtins.str
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator"]) -> None: ...

global___MsgResumeHostZone = MsgResumeHostZone

@typing.final
class MsgResumeHostZoneResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgResumeHostZoneResponse = MsgResumeHostZoneResponse

@typing.final
class MsgRefreshRedemptionRate(google.protobuf.message.Message):
    """RefreshRedemptionRate"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    creator: builtins.str
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator"]) -> None: ...

global___MsgRefreshRedemptionRate = MsgRefreshRedemptionRate

@typing.final
class MsgRefreshRedemptionRateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgRefreshRedemptionRateResponse = MsgRefreshRedemptionRateResponse

@typing.final
class MsgOverwriteDelegationRecord(google.protobuf.message.Message):
    """OverwriteDelegationRecord"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    DELEGATION_RECORD_FIELD_NUMBER: builtins.int
    creator: builtins.str
    @property
    def delegation_record(self) -> stride.staketia.staketia_pb2.DelegationRecord: ...
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        delegation_record: stride.staketia.staketia_pb2.DelegationRecord | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["delegation_record", b"delegation_record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator", "delegation_record", b"delegation_record"]) -> None: ...

global___MsgOverwriteDelegationRecord = MsgOverwriteDelegationRecord

@typing.final
class MsgOverwriteDelegationRecordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgOverwriteDelegationRecordResponse = MsgOverwriteDelegationRecordResponse

@typing.final
class MsgOverwriteUnbondingRecord(google.protobuf.message.Message):
    """OverwriteUnbondingRecord"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    UNBONDING_RECORD_FIELD_NUMBER: builtins.int
    creator: builtins.str
    @property
    def unbonding_record(self) -> stride.staketia.staketia_pb2.UnbondingRecord: ...
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        unbonding_record: stride.staketia.staketia_pb2.UnbondingRecord | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["unbonding_record", b"unbonding_record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator", "unbonding_record", b"unbonding_record"]) -> None: ...

global___MsgOverwriteUnbondingRecord = MsgOverwriteUnbondingRecord

@typing.final
class MsgOverwriteUnbondingRecordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgOverwriteUnbondingRecordResponse = MsgOverwriteUnbondingRecordResponse

@typing.final
class MsgOverwriteRedemptionRecord(google.protobuf.message.Message):
    """OverwriteRedemptionRecord"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    REDEMPTION_RECORD_FIELD_NUMBER: builtins.int
    creator: builtins.str
    @property
    def redemption_record(self) -> stride.staketia.staketia_pb2.RedemptionRecord: ...
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        redemption_record: stride.staketia.staketia_pb2.RedemptionRecord | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["redemption_record", b"redemption_record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator", "redemption_record", b"redemption_record"]) -> None: ...

global___MsgOverwriteRedemptionRecord = MsgOverwriteRedemptionRecord

@typing.final
class MsgOverwriteRedemptionRecordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgOverwriteRedemptionRecordResponse = MsgOverwriteRedemptionRecordResponse

@typing.final
class MsgSetOperatorAddress(google.protobuf.message.Message):
    """SetOperatorAddress"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIGNER_FIELD_NUMBER: builtins.int
    OPERATOR_FIELD_NUMBER: builtins.int
    signer: builtins.str
    operator: builtins.str
    def __init__(
        self,
        *,
        signer: builtins.str = ...,
        operator: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operator", b"operator", "signer", b"signer"]) -> None: ...

global___MsgSetOperatorAddress = MsgSetOperatorAddress

@typing.final
class MsgSetOperatorAddressResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgSetOperatorAddressResponse = MsgSetOperatorAddressResponse
