# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/icaoracle/contract.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fstride/icaoracle/contract.proto\x12\x10stride.icaoracle"R\n\x1cMsgInstantiateOracleContract\x12\x15\n\radmin_address\x18\x01 \x01(\t\x12\x1b\n\x13transfer_channel_id\x18\x02 \x01(\t"T\n\x1cMsgExecuteContractPostMetric\x12\x34\n\x0bpost_metric\x18\x01 \x01(\x0b\x32\x1f.stride.icaoracle.MsgPostMetric"\x7f\n\rMsgPostMetric\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0bmetric_type\x18\x03 \x01(\t\x12\x13\n\x0bupdate_time\x18\x04 \x01(\x03\x12\x14\n\x0c\x62lock_height\x18\x05 \x01(\x03\x12\x12\n\nattributes\x18\x06 \x01(\tB5Z3github.com/Stride-Labs/stride/v24/x/icaoracle/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.icaoracle.contract_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z3github.com/Stride-Labs/stride/v24/x/icaoracle/types"
    )
    _globals["_MSGINSTANTIATEORACLECONTRACT"]._serialized_start = 53
    _globals["_MSGINSTANTIATEORACLECONTRACT"]._serialized_end = 135
    _globals["_MSGEXECUTECONTRACTPOSTMETRIC"]._serialized_start = 137
    _globals["_MSGEXECUTECONTRACTPOSTMETRIC"]._serialized_end = 221
    _globals["_MSGPOSTMETRIC"]._serialized_start = 223
    _globals["_MSGPOSTMETRIC"]._serialized_end = 350
# @@protoc_insertion_point(module_scope)
