"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgInstantiateOracleContract(google.protobuf.message.Message):
    """InstanitateOracleContract is the contract-specific instantiate message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADMIN_ADDRESS_FIELD_NUMBER: builtins.int
    TRANSFER_CHANNEL_ID_FIELD_NUMBER: builtins.int
    admin_address: builtins.str
    transfer_channel_id: builtins.str
    def __init__(
        self,
        *,
        admin_address: builtins.str = ...,
        transfer_channel_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["admin_address", b"admin_address", "transfer_channel_id", b"transfer_channel_id"]) -> None: ...

global___MsgInstantiateOracleContract = MsgInstantiateOracleContract

@typing.final
class MsgExecuteContractPostMetric(google.protobuf.message.Message):
    """ExecuteContractPostMetric is the contract-specific metric update message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POST_METRIC_FIELD_NUMBER: builtins.int
    @property
    def post_metric(self) -> global___MsgPostMetric: ...
    def __init__(
        self,
        *,
        post_metric: global___MsgPostMetric | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["post_metric", b"post_metric"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["post_metric", b"post_metric"]) -> None: ...

global___MsgExecuteContractPostMetric = MsgExecuteContractPostMetric

@typing.final
class MsgPostMetric(google.protobuf.message.Message):
    """Body of PostMetric contract message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    METRIC_TYPE_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str
    metric_type: builtins.str
    update_time: builtins.int
    block_height: builtins.int
    attributes: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.str = ...,
        metric_type: builtins.str = ...,
        update_time: builtins.int = ...,
        block_height: builtins.int = ...,
        attributes: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["attributes", b"attributes", "block_height", b"block_height", "key", b"key", "metric_type", b"metric_type", "update_time", b"update_time", "value", b"value"]) -> None: ...

global___MsgPostMetric = MsgPostMetric
