"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import stride.icaoracle.icaoracle_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Params(google.protobuf.message.Message):
    """Params defines the icaoracle module parameters."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Params = Params

@typing.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines the icaoracle module's genesis state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAMS_FIELD_NUMBER: builtins.int
    ORACLES_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    @property
    def params(self) -> global___Params: ...
    @property
    def oracles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.icaoracle.icaoracle_pb2.Oracle]: ...
    @property
    def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.icaoracle.icaoracle_pb2.Metric]: ...
    def __init__(
        self,
        *,
        params: global___Params | None = ...,
        oracles: collections.abc.Iterable[stride.icaoracle.icaoracle_pb2.Oracle] | None = ...,
        metrics: collections.abc.Iterable[stride.icaoracle.icaoracle_pb2.Metric] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metrics", b"metrics", "oracles", b"oracles", "params", b"params"]) -> None: ...

global___GenesisState = GenesisState
