"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MetricStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MetricStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MetricStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    METRIC_STATUS_UNSPECIFIED: _MetricStatus.ValueType  # 0
    METRIC_STATUS_QUEUED: _MetricStatus.ValueType  # 1
    METRIC_STATUS_IN_PROGRESS: _MetricStatus.ValueType  # 2

class MetricStatus(_MetricStatus, metaclass=_MetricStatusEnumTypeWrapper):
    """MetricStatus indicates whether the Metric update ICA has been sent"""

METRIC_STATUS_UNSPECIFIED: MetricStatus.ValueType  # 0
METRIC_STATUS_QUEUED: MetricStatus.ValueType  # 1
METRIC_STATUS_IN_PROGRESS: MetricStatus.ValueType  # 2
global___MetricStatus = MetricStatus

@typing.final
class Oracle(google.protobuf.message.Message):
    """Oracle structure stores context about the CW oracle sitting a different chain"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_ID_FIELD_NUMBER: builtins.int
    CONNECTION_ID_FIELD_NUMBER: builtins.int
    CHANNEL_ID_FIELD_NUMBER: builtins.int
    PORT_ID_FIELD_NUMBER: builtins.int
    ICA_ADDRESS_FIELD_NUMBER: builtins.int
    CONTRACT_ADDRESS_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    chain_id: builtins.str
    connection_id: builtins.str
    channel_id: builtins.str
    port_id: builtins.str
    ica_address: builtins.str
    contract_address: builtins.str
    active: builtins.bool
    def __init__(
        self,
        *,
        chain_id: builtins.str = ...,
        connection_id: builtins.str = ...,
        channel_id: builtins.str = ...,
        port_id: builtins.str = ...,
        ica_address: builtins.str = ...,
        contract_address: builtins.str = ...,
        active: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["active", b"active", "chain_id", b"chain_id", "channel_id", b"channel_id", "connection_id", b"connection_id", "contract_address", b"contract_address", "ica_address", b"ica_address", "port_id", b"port_id"]) -> None: ...

global___Oracle = Oracle

@typing.final
class Metric(google.protobuf.message.Message):
    """Metric structure stores a generic metric using a key value structure
    along with additional context
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    METRIC_TYPE_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    DESTINATION_ORACLE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str
    metric_type: builtins.str
    update_time: builtins.int
    block_height: builtins.int
    attributes: builtins.str
    destination_oracle: builtins.str
    status: global___MetricStatus.ValueType
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.str = ...,
        metric_type: builtins.str = ...,
        update_time: builtins.int = ...,
        block_height: builtins.int = ...,
        attributes: builtins.str = ...,
        destination_oracle: builtins.str = ...,
        status: global___MetricStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["attributes", b"attributes", "block_height", b"block_height", "destination_oracle", b"destination_oracle", "key", b"key", "metric_type", b"metric_type", "status", b"status", "update_time", b"update_time", "value", b"value"]) -> None: ...

global___Metric = Metric

@typing.final
class RedemptionRateAttributes(google.protobuf.message.Message):
    """Attributes associated with a RedemptionRate metric update"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STTOKEN_DENOM_FIELD_NUMBER: builtins.int
    sttoken_denom: builtins.str
    def __init__(
        self,
        *,
        sttoken_denom: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sttoken_denom", b"sttoken_denom"]) -> None: ...

global___RedemptionRateAttributes = RedemptionRateAttributes
