"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import stride.icaoracle.icaoracle_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryOracleRequest(google.protobuf.message.Message):
    """Query's a specific oracle"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_ID_FIELD_NUMBER: builtins.int
    chain_id: builtins.str
    def __init__(
        self,
        *,
        chain_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chain_id", b"chain_id"]) -> None: ...

global___QueryOracleRequest = QueryOracleRequest

@typing.final
class QueryOracleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORACLE_FIELD_NUMBER: builtins.int
    @property
    def oracle(self) -> stride.icaoracle.icaoracle_pb2.Oracle: ...
    def __init__(
        self,
        *,
        oracle: stride.icaoracle.icaoracle_pb2.Oracle | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["oracle", b"oracle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["oracle", b"oracle"]) -> None: ...

global___QueryOracleResponse = QueryOracleResponse

@typing.final
class QueryAllOraclesRequest(google.protobuf.message.Message):
    """Query's all oracle's"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryAllOraclesRequest = QueryAllOraclesRequest

@typing.final
class QueryAllOraclesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORACLES_FIELD_NUMBER: builtins.int
    @property
    def oracles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.icaoracle.icaoracle_pb2.Oracle]: ...
    def __init__(
        self,
        *,
        oracles: collections.abc.Iterable[stride.icaoracle.icaoracle_pb2.Oracle] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["oracles", b"oracles"]) -> None: ...

global___QueryAllOraclesResponse = QueryAllOraclesResponse

@typing.final
class QueryActiveOraclesRequest(google.protobuf.message.Message):
    """Query's all oracle with a filter for whether they're active"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTIVE_FIELD_NUMBER: builtins.int
    active: builtins.bool
    def __init__(
        self,
        *,
        active: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["active", b"active"]) -> None: ...

global___QueryActiveOraclesRequest = QueryActiveOraclesRequest

@typing.final
class QueryActiveOraclesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORACLES_FIELD_NUMBER: builtins.int
    @property
    def oracles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.icaoracle.icaoracle_pb2.Oracle]: ...
    def __init__(
        self,
        *,
        oracles: collections.abc.Iterable[stride.icaoracle.icaoracle_pb2.Oracle] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["oracles", b"oracles"]) -> None: ...

global___QueryActiveOraclesResponse = QueryActiveOraclesResponse

@typing.final
class QueryMetricsRequest(google.protobuf.message.Message):
    """Query's metric's with optional filters"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METRIC_KEY_FIELD_NUMBER: builtins.int
    ORACLE_CHAIN_ID_FIELD_NUMBER: builtins.int
    metric_key: builtins.str
    oracle_chain_id: builtins.str
    def __init__(
        self,
        *,
        metric_key: builtins.str = ...,
        oracle_chain_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["metric_key", b"metric_key", "oracle_chain_id", b"oracle_chain_id"]) -> None: ...

global___QueryMetricsRequest = QueryMetricsRequest

@typing.final
class QueryMetricsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METRICS_FIELD_NUMBER: builtins.int
    @property
    def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.icaoracle.icaoracle_pb2.Metric]: ...
    def __init__(
        self,
        *,
        metrics: collections.abc.Iterable[stride.icaoracle.icaoracle_pb2.Metric] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["metrics", b"metrics"]) -> None: ...

global___QueryMetricsResponse = QueryMetricsResponse
