# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/stakeibc/gov.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from stride.stakeibc import validator_pb2 as stride_dot_stakeibc_dot_validator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19stride/stakeibc/gov.proto\x12\x0fstride.stakeibc\x1a\x14gogoproto/gogo.proto\x1a\x1fstride/stakeibc/validator.proto"\xb1\x01\n\x15\x41\x64\x64ValidatorsProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\thost_zone\x18\x03 \x01(\t\x12.\n\nvalidators\x18\x04 \x03(\x0b\x32\x1a.stride.stakeibc.Validator\x12#\n\x07\x64\x65posit\x18\x05 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:"deposit":\x0c\x88\xa0\x1f\x00\x98\xa0\x1f\x00\xe8\xa0\x1f\x01"\x8e\x01\n\x11ToggleLSMProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\thost_zone\x18\x03 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\x12#\n\x07\x64\x65posit\x18\x05 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:"deposit":\x0c\x88\xa0\x1f\x00\x98\xa0\x1f\x00\xe8\xa0\x1f\x01\x42\x34Z2github.com/Stride-Labs/stride/v24/x/stakeibc/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "stride.stakeibc.gov_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z2github.com/Stride-Labs/stride/v24/x/stakeibc/types"
    )
    _globals["_ADDVALIDATORSPROPOSAL"].fields_by_name["deposit"]._loaded_options = None
    _globals["_ADDVALIDATORSPROPOSAL"].fields_by_name[
        "deposit"
    ]._serialized_options = b'\362\336\037\016yaml:"deposit"'
    _globals["_ADDVALIDATORSPROPOSAL"]._loaded_options = None
    _globals["_ADDVALIDATORSPROPOSAL"]._serialized_options = (
        b"\210\240\037\000\230\240\037\000\350\240\037\001"
    )
    _globals["_TOGGLELSMPROPOSAL"].fields_by_name["deposit"]._loaded_options = None
    _globals["_TOGGLELSMPROPOSAL"].fields_by_name[
        "deposit"
    ]._serialized_options = b'\362\336\037\016yaml:"deposit"'
    _globals["_TOGGLELSMPROPOSAL"]._loaded_options = None
    _globals["_TOGGLELSMPROPOSAL"]._serialized_options = (
        b"\210\240\037\000\230\240\037\000\350\240\037\001"
    )
    _globals["_ADDVALIDATORSPROPOSAL"]._serialized_start = 102
    _globals["_ADDVALIDATORSPROPOSAL"]._serialized_end = 279
    _globals["_TOGGLELSMPROPOSAL"]._serialized_start = 282
    _globals["_TOGGLELSMPROPOSAL"]._serialized_end = 424
# @@protoc_insertion_point(module_scope)
