# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/stakeibc/ica_account.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!stride/stakeibc/ica_account.proto\x12\x0fstride.stakeibc"u\n\nICAAccount\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\t\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.stride.stakeibc.ICAAccountType\x12\x15\n\rconnection_id\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t*\xab\x01\n\x0eICAAccountType\x12\x0e\n\nDELEGATION\x10\x00\x12\x07\n\x03\x46\x45\x45\x10\x01\x12\x0e\n\nWITHDRAWAL\x10\x02\x12\x0e\n\nREDEMPTION\x10\x03\x12\x1a\n\x16\x43OMMUNITY_POOL_DEPOSIT\x10\x04\x12\x19\n\x15\x43OMMUNITY_POOL_RETURN\x10\x05\x12\x14\n\x10\x43ONVERTER_UNWIND\x10\x06\x12\x13\n\x0f\x43ONVERTER_TRADE\x10\x07\x42\x34Z2github.com/Stride-Labs/stride/v24/x/stakeibc/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.stakeibc.ica_account_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z2github.com/Stride-Labs/stride/v24/x/stakeibc/types"
    )
    _globals["_ICAACCOUNTTYPE"]._serialized_start = 174
    _globals["_ICAACCOUNTTYPE"]._serialized_end = 345
    _globals["_ICAACCOUNT"]._serialized_start = 54
    _globals["_ICAACCOUNT"]._serialized_end = 171
# @@protoc_insertion_point(module_scope)
