# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/stakeibc/packet.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cstride/stakeibc/packet.proto\x12\x0fstride.stakeibc"J\n\x12StakeibcPacketData\x12*\n\x07no_data\x18\x01 \x01(\x0b\x32\x17.stride.stakeibc.NoDataH\x00\x42\x08\n\x06packet"\x08\n\x06NoDataB4Z2github.com/Stride-Labs/stride/v24/x/stakeibc/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.stakeibc.packet_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z2github.com/Stride-Labs/stride/v24/x/stakeibc/types"
    )
    _globals["_STAKEIBCPACKETDATA"]._serialized_start = 49
    _globals["_STAKEIBCPACKETDATA"]._serialized_end = 123
    _globals["_NODATA"]._serialized_start = 125
    _globals["_NODATA"]._serialized_end = 133
# @@protoc_insertion_point(module_scope)
