# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/stakeibc/validator.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fstride/stakeibc/validator.proto\x12\x0fstride.stakeibc\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto"\xfc\x03\n\tValidator\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x07\x61\x64\x64ress\x18\x02 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressString\x12\x0e\n\x06weight\x18\x06 \x01(\x04\x12\x42\n\ndelegation\x18\x05 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\x12T\n\x1cslash_query_progress_tracker\x18\t \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\x12N\n\x16slash_query_checkpoint\x18\x0c \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\x12[\n\x15shares_to_tokens_rate\x18\n \x01(\tB<\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xd2\xb4-\ncosmos.Dec\x12&\n\x1e\x64\x65legation_changes_in_progress\x18\x0b \x01(\x03\x12\x1f\n\x17slash_query_in_progress\x18\r \x01(\x08J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tB4Z2github.com/Stride-Labs/stride/v24/x/stakeibc/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.stakeibc.validator_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z2github.com/Stride-Labs/stride/v24/x/stakeibc/types"
    )
    _globals["_VALIDATOR"].fields_by_name["address"]._loaded_options = None
    _globals["_VALIDATOR"].fields_by_name[
        "address"
    ]._serialized_options = b"\322\264-\024cosmos.AddressString"
    _globals["_VALIDATOR"].fields_by_name["delegation"]._loaded_options = None
    _globals["_VALIDATOR"].fields_by_name[
        "delegation"
    ]._serialized_options = (
        b"\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int"
    )
    _globals["_VALIDATOR"].fields_by_name[
        "slash_query_progress_tracker"
    ]._loaded_options = None
    _globals["_VALIDATOR"].fields_by_name[
        "slash_query_progress_tracker"
    ]._serialized_options = (
        b"\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int"
    )
    _globals["_VALIDATOR"].fields_by_name[
        "slash_query_checkpoint"
    ]._loaded_options = None
    _globals["_VALIDATOR"].fields_by_name[
        "slash_query_checkpoint"
    ]._serialized_options = (
        b"\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int"
    )
    _globals["_VALIDATOR"].fields_by_name[
        "shares_to_tokens_rate"
    ]._loaded_options = None
    _globals["_VALIDATOR"].fields_by_name[
        "shares_to_tokens_rate"
    ]._serialized_options = b"\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\322\264-\ncosmos.Dec"
    _globals["_VALIDATOR"]._serialized_start = 102
    _globals["_VALIDATOR"]._serialized_end = 610
# @@protoc_insertion_point(module_scope)
