"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.sending.transfer_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgCreateTransfer(google.protobuf.message.Message):
    """MsgCreateTransfer is a request type used for initiating new transfers."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSFER_FIELD_NUMBER: builtins.int
    @property
    def transfer(self) -> dydxprotocol.sending.transfer_pb2.Transfer: ...
    def __init__(
        self,
        *,
        transfer: dydxprotocol.sending.transfer_pb2.Transfer | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["transfer", b"transfer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["transfer", b"transfer"]) -> None: ...

global___MsgCreateTransfer = MsgCreateTransfer

@typing.final
class MsgCreateTransferResponse(google.protobuf.message.Message):
    """MsgCreateTransferResponse is a response type used for new transfers."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgCreateTransferResponse = MsgCreateTransferResponse

@typing.final
class MsgDepositToSubaccountResponse(google.protobuf.message.Message):
    """MsgDepositToSubaccountResponse is a response type used for new
    account-to-subaccount transfers.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgDepositToSubaccountResponse = MsgDepositToSubaccountResponse

@typing.final
class MsgWithdrawFromSubaccountResponse(google.protobuf.message.Message):
    """MsgWithdrawFromSubaccountResponse is a response type used for new
    subaccount-to-account transfers.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgWithdrawFromSubaccountResponse = MsgWithdrawFromSubaccountResponse

@typing.final
class MsgSendFromModuleToAccountResponse(google.protobuf.message.Message):
    """MsgSendFromModuleToAccountResponse is a response type used for new
    module-to-account transfers.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgSendFromModuleToAccountResponse = MsgSendFromModuleToAccountResponse
