"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.feetiers.params_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryPerpetualFeeParamsRequest(google.protobuf.message.Message):
    """QueryPerpetualFeeParamsRequest is a request type for the PerpetualFeeParams
    RPC method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryPerpetualFeeParamsRequest = QueryPerpetualFeeParamsRequest

@typing.final
class QueryPerpetualFeeParamsResponse(google.protobuf.message.Message):
    """QueryPerpetualFeeParamsResponse is a response type for the PerpetualFeeParams
    RPC method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAMS_FIELD_NUMBER: builtins.int
    @property
    def params(self) -> dydxprotocol.feetiers.params_pb2.PerpetualFeeParams: ...
    def __init__(
        self,
        *,
        params: dydxprotocol.feetiers.params_pb2.PerpetualFeeParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["params", b"params"]) -> None: ...

global___QueryPerpetualFeeParamsResponse = QueryPerpetualFeeParamsResponse

@typing.final
class QueryUserFeeTierRequest(google.protobuf.message.Message):
    """QueryUserFeeTierRequest is a request type for the UserFeeTier RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    user: builtins.str
    def __init__(
        self,
        *,
        user: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user", b"user"]) -> None: ...

global___QueryUserFeeTierRequest = QueryUserFeeTierRequest

@typing.final
class QueryUserFeeTierResponse(google.protobuf.message.Message):
    """QueryUserFeeTierResponse is a request type for the UserFeeTier RPC method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    TIER_FIELD_NUMBER: builtins.int
    index: builtins.int
    """Index of the fee tier in the list queried from PerpetualFeeParams."""
    @property
    def tier(self) -> dydxprotocol.feetiers.params_pb2.PerpetualFeeTier: ...
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        tier: dydxprotocol.feetiers.params_pb2.PerpetualFeeTier | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tier", b"tier"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["index", b"index", "tier", b"tier"]) -> None: ...

global___QueryUserFeeTierResponse = QueryUserFeeTierResponse
