# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stride/autopilot/params.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dstride/autopilot/params.proto\x12\x10stride.autopilot\x1a\x14gogoproto/gogo.proto"=\n\x06Params\x12\x17\n\x0fstakeibc_active\x18\x01 \x01(\x08\x12\x14\n\x0c\x63laim_active\x18\x02 \x01(\x08:\x04\x98\xa0\x1f\x00\x42\x35Z3github.com/Stride-Labs/stride/v24/x/autopilot/typesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "stride.autopilot.params_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z3github.com/Stride-Labs/stride/v24/x/autopilot/types"
    )
    _globals["_PARAMS"]._loaded_options = None
    _globals["_PARAMS"]._serialized_options = b"\230\240\037\000"
    _globals["_PARAMS"]._serialized_start = 73
    _globals["_PARAMS"]._serialized_end = 134
# @@protoc_insertion_point(module_scope)
