"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Params(google.protobuf.message.Message):
    """Params defines the parameters for the module.
    next id: 1
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STAKEIBC_ACTIVE_FIELD_NUMBER: builtins.int
    CLAIM_ACTIVE_FIELD_NUMBER: builtins.int
    stakeibc_active: builtins.bool
    """optionally, turn off each module"""
    claim_active: builtins.bool
    def __init__(
        self,
        *,
        stakeibc_active: builtins.bool = ...,
        claim_active: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["claim_active", b"claim_active", "stakeibc_active", b"stakeibc_active"]) -> None: ...

global___Params = Params
