"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dydxprotocol.bridge.bridge_event_info_pb2
import dydxprotocol.bridge.params_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines the bridge module's genesis state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_PARAMS_FIELD_NUMBER: builtins.int
    PROPOSE_PARAMS_FIELD_NUMBER: builtins.int
    SAFETY_PARAMS_FIELD_NUMBER: builtins.int
    ACKNOWLEDGED_EVENT_INFO_FIELD_NUMBER: builtins.int
    @property
    def event_params(self) -> dydxprotocol.bridge.params_pb2.EventParams:
        """The parameters of the module."""

    @property
    def propose_params(self) -> dydxprotocol.bridge.params_pb2.ProposeParams: ...
    @property
    def safety_params(self) -> dydxprotocol.bridge.params_pb2.SafetyParams: ...
    @property
    def acknowledged_event_info(self) -> dydxprotocol.bridge.bridge_event_info_pb2.BridgeEventInfo:
        """Acknowledged event info that stores:
        - the next event ID to be added to consensus.
        - Ethereum block height of the most recently acknowledged bridge event.
        """

    def __init__(
        self,
        *,
        event_params: dydxprotocol.bridge.params_pb2.EventParams | None = ...,
        propose_params: dydxprotocol.bridge.params_pb2.ProposeParams | None = ...,
        safety_params: dydxprotocol.bridge.params_pb2.SafetyParams | None = ...,
        acknowledged_event_info: dydxprotocol.bridge.bridge_event_info_pb2.BridgeEventInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["acknowledged_event_info", b"acknowledged_event_info", "event_params", b"event_params", "propose_params", b"propose_params", "safety_params", b"safety_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["acknowledged_event_info", b"acknowledged_event_info", "event_params", b"event_params", "propose_params", b"propose_params", "safety_params", b"safety_params"]) -> None: ...

global___GenesisState = GenesisState
