"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dydxprotocol.bridge.bridge_event_pb2
import dydxprotocol.bridge.params_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgAcknowledgeBridges(google.protobuf.message.Message):
    """MsgAcknowledgeBridges is the Msg/AcknowledgeBridges request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dydxprotocol.bridge.bridge_event_pb2.BridgeEvent]:
        """The events to acknowledge."""

    def __init__(
        self,
        *,
        events: collections.abc.Iterable[dydxprotocol.bridge.bridge_event_pb2.BridgeEvent] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["events", b"events"]) -> None: ...

global___MsgAcknowledgeBridges = MsgAcknowledgeBridges

@typing.final
class MsgAcknowledgeBridgesResponse(google.protobuf.message.Message):
    """MsgAcknowledgeBridgesResponse is the Msg/AcknowledgeBridgesResponse response
    type.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgAcknowledgeBridgesResponse = MsgAcknowledgeBridgesResponse

@typing.final
class MsgCompleteBridge(google.protobuf.message.Message):
    """MsgCompleteBridge is the Msg/CompleteBridgeResponse request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    authority: builtins.str
    @property
    def event(self) -> dydxprotocol.bridge.bridge_event_pb2.BridgeEvent:
        """The event to complete."""

    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        event: dydxprotocol.bridge.bridge_event_pb2.BridgeEvent | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["event", b"event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "event", b"event"]) -> None: ...

global___MsgCompleteBridge = MsgCompleteBridge

@typing.final
class MsgCompleteBridgeResponse(google.protobuf.message.Message):
    """MsgCompleteBridgeResponse is the Msg/CompleteBridgeResponse response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgCompleteBridgeResponse = MsgCompleteBridgeResponse

@typing.final
class MsgUpdateEventParams(google.protobuf.message.Message):
    """MsgUpdateEventParams is the Msg/UpdateEventParams request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    authority: builtins.str
    @property
    def params(self) -> dydxprotocol.bridge.params_pb2.EventParams:
        """The parameters to update. Each field must be set."""

    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        params: dydxprotocol.bridge.params_pb2.EventParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "params", b"params"]) -> None: ...

global___MsgUpdateEventParams = MsgUpdateEventParams

@typing.final
class MsgUpdateEventParamsResponse(google.protobuf.message.Message):
    """MsgUpdateEventParamsResponse is the Msg/UpdateEventParams response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgUpdateEventParamsResponse = MsgUpdateEventParamsResponse

@typing.final
class MsgUpdateProposeParams(google.protobuf.message.Message):
    """MsgUpdateProposeParams is the Msg/UpdateProposeParams request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    authority: builtins.str
    @property
    def params(self) -> dydxprotocol.bridge.params_pb2.ProposeParams:
        """The parameters to update. Each field must be set."""

    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        params: dydxprotocol.bridge.params_pb2.ProposeParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "params", b"params"]) -> None: ...

global___MsgUpdateProposeParams = MsgUpdateProposeParams

@typing.final
class MsgUpdateProposeParamsResponse(google.protobuf.message.Message):
    """MsgUpdateProposeParamsResponse is the Msg/UpdateProposeParams response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgUpdateProposeParamsResponse = MsgUpdateProposeParamsResponse

@typing.final
class MsgUpdateSafetyParams(google.protobuf.message.Message):
    """MsgUpdateSafetyParams is the Msg/UpdateSafetyParams request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    authority: builtins.str
    @property
    def params(self) -> dydxprotocol.bridge.params_pb2.SafetyParams:
        """The parameters to update. Each field must be set."""

    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        params: dydxprotocol.bridge.params_pb2.SafetyParams | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "params", b"params"]) -> None: ...

global___MsgUpdateSafetyParams = MsgUpdateSafetyParams

@typing.final
class MsgUpdateSafetyParamsResponse(google.protobuf.message.Message):
    """MsgUpdateSafetyParamsResponse is the Msg/UpdateSafetyParams response type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgUpdateSafetyParamsResponse = MsgUpdateSafetyParamsResponse
