"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import tendermint.crypto.proof_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgSubmitQueryResponse(google.protobuf.message.Message):
    """MsgSubmitQueryResponse represents a message type to fulfil a query request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_ID_FIELD_NUMBER: builtins.int
    QUERY_ID_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    PROOF_OPS_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    FROM_ADDRESS_FIELD_NUMBER: builtins.int
    chain_id: builtins.str
    query_id: builtins.str
    result: builtins.bytes
    height: builtins.int
    from_address: builtins.str
    @property
    def proof_ops(self) -> tendermint.crypto.proof_pb2.ProofOps: ...
    def __init__(
        self,
        *,
        chain_id: builtins.str = ...,
        query_id: builtins.str = ...,
        result: builtins.bytes = ...,
        proof_ops: tendermint.crypto.proof_pb2.ProofOps | None = ...,
        height: builtins.int = ...,
        from_address: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["proof_ops", b"proof_ops"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["chain_id", b"chain_id", "from_address", b"from_address", "height", b"height", "proof_ops", b"proof_ops", "query_id", b"query_id", "result", b"result"]) -> None: ...

global___MsgSubmitQueryResponse = MsgSubmitQueryResponse

@typing.final
class MsgSubmitQueryResponseResponse(google.protobuf.message.Message):
    """MsgSubmitQueryResponseResponse defines the MsgSubmitQueryResponse response
    type.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgSubmitQueryResponseResponse = MsgSubmitQueryResponseResponse
