"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import stride.interchainquery.v1.genesis_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryPendingQueriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___QueryPendingQueriesRequest = QueryPendingQueriesRequest

@typing.final
class QueryPendingQueriesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PENDING_QUERIES_FIELD_NUMBER: builtins.int
    @property
    def pending_queries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[stride.interchainquery.v1.genesis_pb2.Query]: ...
    def __init__(
        self,
        *,
        pending_queries: collections.abc.Iterable[stride.interchainquery.v1.genesis_pb2.Query] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pending_queries", b"pending_queries"]) -> None: ...

global___QueryPendingQueriesResponse = QueryPendingQueriesResponse
